### ISSUE TITLE
Batching happens only opportunistically

### ISSUE THREAD

**Issue by eriklee** [kafka4beam/brod#104]
It looks like brod will try to send produce requests as quickly as possible. Notably, in the case where requiredAcks = 0 it will just send everything individually. Many other kafka libraries seem to offer something like lingerMS which lets the library batch things more effectively. Then a produce request is only set after lingerMS milliseconds have passed or the buffer gets over some predetermined size. The benefits of this are reduced network traffic and load on the brokers, and it makes the compression options much more effective.

Is this be something brod might support? It's something I could potentially work on if it turns out to be helpful for my company, but it's a slightly larger feature so I thought I'd check first that it wasn't being worked on and would potentially be accepted.

**Comment by zmstone** [comment]
Yes, this could be helpful especially when compression is enabled.
It should be configurable and perhaps switched off by default.
Please send the PR to 2.2-dev if you get to it before us.

**Comment by zmstone** [comment]
@eriklee We are releasing 2.2 soon. Pushing this to 2.3.

**Comment by eriklee** [comment]
Ok. Things are working reasonably well for us at the moment so I don't think it's going to be a priority for me either for now.
