### ISSUE TITLE
Problem compiling Snappyer in v2.2.1 in Mac OS X

### ISSUE THREAD

**Issue by onetroll** [kafka4beam/brod#117]
Hello, I'm trying to update brod to v2.2.1 and I've got error when trying to compile snappyer on Mac OS X (El Capitan). I'm using Hex in an Elixir project.

A co-worker that also uses Mac OS X has the same problem. Meanwhile, it seems that compiles perfectly in another co-worker's machine that uses Ubuntu (but our acceptance tests stop working with message parse errors ...)

With version 2.1.8 everything works perfectly.

This is the output that I got:

_==> snappyer (compile)
 DEPEND snappyer.d
 ERLC   snappyer.erl
 APP    snappyer.app.src
 CPP    snappy-sinksource.cc
clang: warning: optimization flag '-finline-functions' is not supported
 CPP    snappy-stubs-internal.cc
clang: warning: optimization flag '-finline-functions' is not supported
 CPP    snappy.cc
clang: warning: optimization flag '-finline-functions' is not supported
 CPP    snappyer.cc
clang: warning: optimization flag '-finline-functions' is not supported
 LD     snappyer.so
Undefined symbols for architecture x86_64:
  "_enif_alloc_binary", referenced from:
      SnappyNifSink::SnappyNifSink(enif_environment_t_) in snappyer.o
      SnappyNifSink::SnappyNifSink(enif_environment_t_) in snappyer.o
      _snappy_compress_erl in snappyer.o
      _snappy_decompress_erl in snappyer.o
  "_enif_inspect_iolist_as_binary", referenced from:
      _snappy_compress_erl in snappyer.o
      _snappy_decompress_erl in snappyer.o
      _snappy_uncompressed_length_erl in snappyer.o
      _snappy_is_valid in snappyer.o
  "_enif_make_atom", referenced from:
      _snappy_compress_erl in snappyer.o
      _snappy_decompress_erl in snappyer.o
      _snappy_uncompressed_length_erl in snappyer.o
      _snappy_is_valid in snappyer.o
  "_enif_make_badarg", referenced from:
      _snappy_compress_erl in snappyer.o
      _snappy_decompress_erl in snappyer.o
      _snappy_uncompressed_length_erl in snappyer.o
      _snappy_is_valid in snappyer.o
  "_enif_make_binary", referenced from:
      _snappy_compress_erl in snappyer.o
      _snappy_decompress_erl in snappyer.o
  "_enif_make_existing_atom", referenced from:
      _snappy_compress_erl in snappyer.o
      _snappy_decompress_erl in snappyer.o
      _snappy_uncompressed_length_erl in snappyer.o
      _snappy_is_valid in snappyer.o
  "_enif_make_tuple", referenced from:
      _snappy_compress_erl in snappyer.o
      _snappy_decompress_erl in snappyer.o
      _snappy_uncompressed_length_erl in snappyer.o
      _snappy_is_valid in snappyer.o
  "_enif_make_ulong", referenced from:
      _snappy_uncompressed_length_erl in snappyer.o
  "_enif_realloc_binary", referenced from:
      SnappyNifSink::GetAppendBuffer(unsigned long, char_) in snappyer.o
      SnappyNifSink::getBin() in snappyer.o
      _snappy_compress_erl in snappyer.o
  "_enif_release_binary", referenced from:
      SnappyNifSink::~SnappyNifSink() in snappyer.o
      SnappyNifSink::~SnappyNifSink() in snappyer.o
      SnappyNifSink::~SnappyNifSink() in snappyer.o
      _snappy_compress_erl in snappyer.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *_\* [/Users/samuel/cfadapter/deps/snappyer/priv/snappyer.so] Error 1
ERROR: Command [compile] failed!
==> cfadapter
*\* (Mix) Could not compile dependency :snappyer, "/Users/samuel/.mix/rebar compile skip_deps=true deps_dir="/Users/samuel/cfadapter/_build/dev/lib"" command failed. You can recompile this dependency with "mix deps.compile snappyer", update it with "mix deps.update snappyer" or clean it with "mix deps.clean snappyer"_

I'm not used to NIFs in Erlang/Elixir, so I'm not sure where is the problem. Any idea???

Thank you.

**Comment by zmstone** [comment]
thans for reporting this.
trying to setup a test bed in my mac

**Comment by zmstone** [comment]
snappyer 1.1.3-1.0.4 has been published to hex.
and kfka_protocol patch is coming up: https://github.com/klarna/kafka_protocol/pull/18
