### ISSUE TITLE
How to track the acknowledged offsets from a brod topic subscriber

### ISSUE THREAD

**Issue by sdball** [kafka4beam/brod#127]
Hello! I'm making a thin Elixir wrapper around brod for local Kafka work. I've got a Consumer module using `brod_topic_subscriber` to consume messages just fine. Right now I'm using the `{:ok, :ack, state}` flow so messages are acknowledged immediately after processing.

My expectation was that if something goes wrong during message processing then the given message(s) would be unacknowledged and redelivered.

That seems to be the case while my application is running. Messages fail to process and new messages add to the message set that's pending processing.

But if I restart the Elixir application then those unacknowledged messages are not reprocessed.

I've traced it to my setting `[]` as the uncommitted offsets in the `init` function of my brod topic subscriber module. Is there a way to have the topic subscriber track the offsets that have been acknowledged? Or is a topic subscribe expected to maintain its own acknowledged offsets? Do I really want to be using a group subscriber here?

**Comment by zmstone** [comment]
You may want to write the processed offsets to a local storage (e.g. in test/brod_demo_topic_subscriber.erl, it writes offsets to file).
The init/2 API should retrun `{ok, CommittedOffsets, CbState}` where `CommittedOffsets` is to indicate brod from where + 1 it should start fetching messages. 

Another option is to use group subscriber with offsets committed to kafka.
(see test/brod_demo_group_subscriber_koc.erl for example).

**Comment by zmstone** [comment]
If there is no `CommittedOffset` given and the consumer config is using defulat `begin_offset` option, the unacknowledged messages will be skipped because `brod_consumer` will by default fetch from `latest` offset.

A side note: this is an at-least-once delivery system, be ready for redelivery/duplication.

**Comment by sdball** [comment]
Ok great! Thanks for the insight :thumbsup: :heart:

**Comment by sdball** [comment]
I've switched to the group subscriber behavior and that's working very well for the synchronous ack flow.

I'd like to support async acks to commit offsets back to Kafka. But it looks like I'd have to manually track the pid of the group subscriber process on order to call `ack/4`.

Since `brod_group_subscriber` doesn't allow for setting a registered name on `start_link` is there a good way to track the pid when the subscriber process is supervised?

I could do something like make a wrapper module that I start and name with my supervision tree which then starts the brod group subscriber and tracks the pid in its state. But I'm hoping there's a cleaner way that should be done.

**Comment by zmstone** [comment]
I assume you have message processors spawned in a pool or under some other supervisor.
A typical work flow is to forward the message with `self()` pid.
e.g. `erlang:send(MessageHandlerPid, {_SubscriberPid=self(), Topic, Partition, KafkaMessage}).`
Then the message handler can call `brod_group_subscriber:ack(SubscriberPid, Topic, Partition, KafkaMessage#kafka_message.offset)` to ack, where SubscriberPid is the first element in the received tuple message.

Or if you really want to have a global name registered, take a look at the gen_server implementation in `brod_group_subscriber.erl`
call `gen_server:start_link({local, RegName}, brod_group_subscriber, Args, [])` yourself.
But I can't really say this is a good practice.

**Comment by zmstone** [comment]
the koc demo is using async ack.

**Comment by zmstone** [comment]
ah, sorry, koc demo has the subscriber pid passed through the init arguments of the handlers not by sending the pid to handlers.

**Comment by sdball** [comment]
Ahh, thanks! I was completely overlooking the now obvious solution to send the pid along to the message handler. That sounds much nicer than using a global name or introducing a registry.
