### ISSUE TITLE
Why I can not compile???

### ISSUE THREAD

**Issue by yunnet** [kafka4beam/brod#128]
$ rebar3 compile
===> Verifying dependencies...
===> Fetching kafka_protocol ({pkg,<<"kafka_protocol">>,<<"0.7.3">>})
===> Download error, using cached file at c:/Users/Net/.cache/rebar3/hex/default/packages/kafka_protocol-0.7.3.tar
===> Fetching supervisor3 ({pkg,<<"supervisor3">>,<<"1.1.3">>})
===> Downloaded package, caching at c:/Users/Net/.cache/rebar3/hex/default/packages/supervisor3-1.1.3.tar
===> Fetching snappyer ({pkg,<<"snappyer">>,<<"1.1.3-1.0.4">>})
===> Downloaded package, caching at c:/Users/Net/.cache/rebar3/hex/default/packages/snappyer-1.1.3-1.0.4.tar
===> Compiling supervisor3
**===> Compiling snappyer
MAKE Version 5.2  Copyright (c) 1987, 2000 Borland
Error makefile 15: Command syntax error
Error makefile 18: Command syntax error
Error makefile 20: Command syntax error
**\* 3 errors during make ***
===> Hook for compile failed!**

**Comment by id** [comment]
Looks like make 5.2 from Borland can't read our Makefile. Can you try to install http://gnuwin32.sourceforge.net/packages/make.htm and see if it works? Don't have a windows PC at hand, but I'll try to figure something out if this does not work.

Also, could you provide more details? Windows version, whether you use cygwin, etc.

**Comment by zmstone** [comment]
Here is the on-windows guide from erlang.mk:  https://erlang.mk/guide/installation.html#_on_windows
Loading nif from dll can't be supported without a significant change to Makefile and source code.

On the other hand, we should probably support a global setting to enable/disable snappy.
when disabled, kafka_protocol should not download the dependency and not compile the snappy compression/decompression clauses either.

**Comment by yunnet** [comment]
Thank you for your help, I try again

**Comment by zmstone** [comment]
@yunnet Did it work out for you?
I have tried to make `snappyer` dependency optional in `Makefile` and `rebar.config.script` of the library `kafka_protocol`, which worked for `erlang.mk` and `rebar` but not `rebar3` (because it downloads dependencies recursively from hex).

If you do not need snappy compression in your project, you can try to manually remove the dependency, (also delete the entry from your project `rebar.lock`).
