### ISSUE TITLE
create start_client return PID

### ISSUE THREAD

**Issue by turtleDeng** [kafka4beam/brod#135]
Hi
  Whether it can support the start_client without parameters, start_client function returns the client PID, which will help pre-access connection pool

**Comment by zmstone** [comment]
Not sure I understand your use case.
There is `start_link_client/3` which returns pid (the api is deprecated though).
However, you still have to give them unique `client_id` because `brod_client` requires a named ETS table.
EDIT: `brod_client` uses the client id as the ets table name.

**Comment by turtleDeng** [comment]
thx
