### ISSUE TITLE
client topic producer relationship

### ISSUE THREAD

**Issue by turtleDeng** [kafka4beam/brod#136]
Hello
   I asked a framework on the issue, a client, in the same topic, there can be only one producer. But in many production processes, a topic may require multiple producers, may I ask what is your good idea?

**Comment by zmstone** [comment]
Hi
1. For one `brod_client`, there is one producer process per-partition, NOT per-topic.
2. You may start as many `brod_client` as you want to have more producers per-partition.
The way to scale kafka volume/throughput is to add more partitions, not by adding more producers.
With tuned producer config, It's unlikely you have to spawn two producers for one partition.

**Comment by zmstone** [comment]
the overview process tree diagram in README.md should give you a better picture how the processes are organised in brod.
