### ISSUE TITLE
calling brod:start_client(Hosts, undefined) returns already_started

### ISSUE THREAD

**Issue by zsoci** [kafka4beam/brod#142]
1> H = [{"localhost",9092}].
[{"localhost",9092}]
2> brod:start_client(H, undefined).
{error,{{already_started,undefined},
        {child,undefined,undefined,
               {brod_client,start_link,[[{"localhost",9092}],undefined,[]]},
               {permanent,10},
               5000,worker,
               [brod_client]}}}
3> brod:start_client(H, anyclient).
ok

**Comment by zmstone** [comment]
I think it's a bug OTP should fix:
```
1> gen_server:start_link({local, undefined}, x, y, []).
{error,{already_started,undefined}}
```

**Comment by zsoci** [comment]
Good catch. tx!
