### ISSUE TITLE
feature request: allow option to disable brod_reply acks

### ISSUE THREAD

**Issue by byronpc** [kafka4beam/brod#153]
is it possible to create an option to disable brod_reply acks back to the sender? the reason for this is we're using kafka for some statistical events where the acknowledgments to the callers aren't really necessary and only causes additional traffic internally.

**Comment by zmstone** [comment]
Sure we can add one.

But before jumping into the code I'd like to ask:
Is `{required_acks, 0}` in producer config and call `brod:produce_sync` API still too much overhead for you ?
Sending data down to the socket without any pushback feels quite risky.

**Comment by byronpc** [comment]
i'm using required_acks 0. If i'm not mistaken brod:produce_sync basically directly handles the receive part in the function which is just the same right since the ack will still be returned to the calling pid.

as it is right now i use 'produce' on a gen_fsm state. and everytime i send an event, i receive a {brod_produce_reply, call_ref, brod_produce_req_acked} in the handle_info. on our particular scenario, this is actually unnecessary overhead.

i'm not sure if it's related to required_acks 0 but i'm talking about 'reply_acked' function in the brod_producer_buffer.erl file.

Perhaps an option retain it for errors but skip it for successes? :)

Many thanks

**Comment by zmstone** [comment]
Sorry, I remembered wrong. The acked reply is sent back to the caller immediately after the message is sent to `brod_sock` process (not right after buffered).
`brod_sock` is shared with other callers sending messages to other topic-partitions concurrently.

**Comment by byronpc** [comment]
OK. Thanks for your reply.

I understand your scenario. On our use case though, it's more of a fire and forget kind of thing, where even if kafka is failing, and brod is failing, it should be fine because the data is not super critical that we want to add another layer of queue in the fsm to collect all the stats. It will also be quite redundant to have one queue in brod and another one on each of the fsms running no? The fsm itself is important and we want to avoid adding more logic that could potentially crash the fsm itself. But ofcourse the current implementation works, it's just that I wanted to avoid the additional messages that are being sent (regardless of whether handled in handle_info or via receive).

But anyway, thanks. I'll make do with this for the mean time:)

**Comment by zmstone** [comment]
Fair enough, we'll perhaps add a `fire_and_forget` option to the producer config.
Targeting 2.3

**Comment by zmstone** [comment]
sorry, this has took embarrassingly long.
Added two brod:produce_no_ack APIs in #276
