### ISSUE TITLE
maybe_send_fetch_request function may send multi fetch request with the same begin_offset if prefetch_count is more than 1

### ISSUE THREAD

**Issue by theorix** [kafka4beam/brod#157]
when I set prefetch_count with 200, this may happen in this order:
1. when ack offset 1, function 'maybe_send_fetch_request' will send a fetch request
2. if ack offset 2 happened before receive the fetch response, function 'maybe_send_fetch_request' will send a fetch request with the same begin_offset
3. this may cause fetch request for the same begin_offset be sent for 200 times.

**Comment by zmstone** [comment]
yes, we need to fix this.
but may I ask why would you ack before any message is fetched ?

**Comment by zmstone** [comment]
never mind, got it.

**Comment by theorix** [comment]
thanks for fix^_^
