### ISSUE TITLE
Using min_bytes in consumer seems to slow production

### ISSUE THREAD

**Issue by Kwisatx** [kafka4beam/brod#161]
Hello,

We've been playing around with sleep_timeout, min_bytes and max_wait_time in our application, firstly to get our unittests working (with the default min_bytes = 0 and sleep_timeout = 1s and the low number of throughput in the tests some message treatment was taking too long) and then to see what would be best for our use case in production.

One of our first tests was to set min_bytes to 1 and max_wait_time to 500ms (expecting no issues as any message would be treated immediately as long as messages arrived fairly regularly). However, our unittests would fail with those parameters, and after investigating it turned out not to be an issue with consumption (incoming messages from kafka were treated in a timely fashion) but with production.

After adding some logging in brod, we determined that the delay was specifically located in the waiting for an ack after producing (ie between the end of `brod_producer:handle_produce` and `brod_producer:handle_info({msg, Pid, CorrId, #kpro_ProduceResponse{} = R}`), and could reach times proportional to max_wait_time (with a max_wait_time of 500ms we would see some production times of up to 800ms and with a max_wait_time of 50ms we would see some production times of up to 120ms for example).

Is there a reason that the max_wait_time of the consumer would affect the time it takes to produce a message / receive the production ack?

We are currently using brod 2.2.10 with kafka 0.9.0.1 in a docker for the tests.
The client config: `brod:start_client(HostPorts, brod_client, [{auto_start_producers, true}, {default_producer_config, []}])`

**Comment by zmstone** [comment]
Hi @Kwisatx

Likely irrelevant: are your producer(s) and consumer(s) running in the same `brod_client` ?

All requests are sent async-ly to kafka, also producers and consumers are running in different processes.

Hunch: This is probably a behaviour of kafka. i.e. how it accumulates batches before sending replies (produce-response to producers, and fetch-response to consumers). The max_wait_time sent in the fetch request might affect how kafka tries to optimise batches.

But we'll see if we can prove it by sending messages from for example a Java client.

**Comment by Kwisatx** [comment]
Hi @zmstone 

Yes they do run with the same brod_client (the consumers are created for the same client that auto starts the producer). I suppose it wouldn't hurt to try with a second client for the consumers just to see what happens.

**Comment by zmstone** [comment]
right.
please also try brod 2.2.12.
the bug fixed in 2.2.12 might affect consumer performance.

**Comment by Kwisatx** [comment]
Well that was far from being an irrelevant question, separating the consumers and the producers on different clients made the problem completely disappear (producing is back to being nigh on instantaneous, just a few milliseconds whatever the max_wait_time).

I also tried updating to brod 2.2.12, but I had the same issues when using a single client, and the same success when using 2 different clients.

**Comment by zmstone** [comment]
That was quick!
Thanks a lot for testing it out!
Now we know where to look (brod_sock)
Or it could still be kafka to blame :)

**Comment by zmstone** [comment]
Hi @Kwisatx do you mind sharing your test code ? if it fits a gist ?

**Comment by Kwisatx** [comment]
Ouf, I'm not sure what I can do to pare it down to something bite-sized :stuck_out_tongue: (and shareable). 
I'll see if I can extract what is needed to reproduce the issue.

**Comment by zmstone** [comment]
take time, now rush, thanks a lot!
