### ISSUE TITLE
Can't seem to get group subscriber working. 

### ISSUE THREAD

**Issue by cdegroot** [kafka4beam/brod#171]
I'm trying to get a group subscriber working - what I'm getting is a very fast loop of roughly the following: 

```
21:29:51.650 [info]  group coordinator (groupId=schedulex_work_consumer,memberId=,generation=0,pid=#PID<0.189.0>):
connected to group coordinator oldmac.yyz-1.evrl.ca:9092

21:29:51.659 [info]  group coordinator (groupId=schedulex_work_consumer,memberId=,generation=0,pid=#PID<0.189.0>):
failed to join group
reason:{:sock_down,
 {:function_clause,
  [{:kpro_structs, :encode, [string: nil],
    [file: 'src/kpro_structs.erl', line: 10]},
   {:kpro, :"-encode/1-lc$^0/1-0-", 2, [file: 'src/kpro.erl', line: 338]},
   {:kpro, :encode, 1, [file: 'src/kpro.erl', line: 338]},
   {:kpro_structs, :encode, 1, [file: 'src/kpro_structs.erl', line: 144]},
   {:kpro, :encode, 1, [file: 'src/kpro.erl', line: 384]},
   {:kpro, :"-encode/1-lc$^1/1-1-", 1, [file: 'src/kpro.erl', line: 341]},
   {:kpro, :encode, 1, [file: 'src/kpro.erl', line: 341]},
   {:kpro_structs, :encode, 1, [file: 'src/kpro_structs.erl', line: 117]},
   {:kpro, :encode_request, 1, [file: 'src/kpro.erl', line: 206]},
   {:brod_sock, :handle_msg, 3, [file: 'src/brod_sock.erl', line: 289]},
   {:brod_sock, :init, 5, [file: 'src/brod_sock.erl', line: 191]},
   {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}

21:29:51.660 [info]  group coordinator (groupId=schedulex_work_consumer,memberId=,generation=0,pid=#PID<0.189.0>):
re-joining group, reason:{:sockent_down,
 {:function_clause,
  [{:kpro_structs, :encode, [string: nil],
    [file: 'src/kpro_structs.erl', line: 10]},
   {:kpro, :"-encode/1-lc$^0/1-0-", 2, [file: 'src/kpro.erl', line: 338]},
   {:kpro, :encode, 1, [file: 'src/kpro.erl', line: 338]},
   {:kpro_structs, :encode, 1, [file: 'src/kpro_structs.erl', line: 144]},
   {:kpro, :encode, 1, [file: 'src/kpro.erl', line: 384]},
   {:kpro, :"-encode/1-lc$^1/1-1-", 1, [file: 'src/kpro.erl', line: 341]},
   {:kpro, :encode, 1, [file: 'src/kpro.erl', line: 341]},
   {:kpro_structs, :encode, 1, [file: 'src/kpro_structs.erl', line: 117]},
   {:kpro, :encode_request, 1, [file: 'src/kpro.erl', line: 206]},
   {:brod_sock, :handle_msg, 3, [file: 'src/brod_sock.erl', line: 289]},
   {:brod_sock, :init, 5, [file: 'src/brod_sock.erl', line: 191]},
   {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}

21:29:51.660 [info]  group coordinator (groupId=schedulex_work_consumer,memberId=,generation=0,pid=#PID<0.189.0>):
connected to group coordinator oldmac.yyz-1.evrl.ca:9092
```

This just continues and continues, without ever stopping. Other Kafka stuff is working, so it seems to be ok. The code that sets up the consumer seems ordinary to me and matches with what I've seen in other examples: 

```
   :ok = :brod.start_client(brokers, @client_name)
    {:ok, _pid} = :brod.start_link_group_subscriber(
      @client_name, @group_name, [work_topic],
      @consumer_config, @group_config, __MODULE__, [])
```

For context, this is in a WIP little project I'm working on. The code above is in https://github.com/cdegroot/schedulex/blob/master/lib/schedulex/brod_consumer.ex, and the project can be pulled and `mix test test/schedulex/brod_consumer_test.exs` - at least on my development environment - reproduces the problem by rapidly looping. 

The strange thing is - I did a quick look with Wireshark, and it looks like Brod opens a socket to Kafka successfully, then closes it immediately. The other strange thing is that the maximum limit and delays I've setup aren't kicking in - it just loops as fast as possible. 

Am I missing something here?

**Comment by cdegroot** [comment]
Nothing to see, please move on. `work_topic` was null ;-). 

However, it's still a bit of an unexpected failure mode - took me two hours to find it :). Argument validation needed?

**Comment by zmstone** [comment]
will add a validation.

**Comment by zmstone** [comment]
btw, group coordinator is link-started to your group subscriber process and establishes its own connection to one of the kafka brokers (the elected coordinator broker).
you didn't see delay between the restarts probably because you don't have a delayed restart for your subscriber process ?.

**Comment by cdegroot** [comment]
Probably not - I'd need to dig into what was exactly crashing/looping and why, after all that puzzling I was already happy to find the culprit and move on :-). 

(and at the end of it all, I probably need to reimplement the group subscriber anyway for my project as I need to have a very managed lifecycle, which includes knowing which partitions are assigned, doing some setup work, only then starting to consume, etcetera; should be pretty straightforward thanks to your split of subscriber and coordinator, I think I only should need to duplicate the simple stuff)

**Comment by zmstone** [comment]
Ah, the default re-join delay is 1 second. And when socket is down, the re-join counter is set back to 0, so it'll never reach the max re-join attempt threshold.
Will fix this too.

It'd be more flexible for you if you implement the `brod_group_member` behaviour.
And if you messages are of very small size, it's probably better to dispatch message-sets to workers instead of individual messages.
Here is another group member example: https://github.com/klarna/brucke/blob/1.5.1/src/brucke_member.erl

**Comment by cdegroot** [comment]
Yup, already looked at Brucke. Doesn't look too hard. All I now need is a little bit of time to finish this :)
