### ISSUE TITLE
Support Kafka cluster

### ISSUE THREAD

**Issue by turtleDeng** [kafka4beam/brod#175]
If the code is not able to support Kafka cluster?
`
brod:start_client([{"127.0.0.1", 9092},{"127.0.0.2", 9092},{"127.0.0.3", 9092}], pname,  [])
`

**Comment by zmstone** [comment]
what was the error?

**Comment by zmstone** [comment]
I tested it, it should work.
In my test, I have only ONE kafka node listening on `0.0.0.0:9092`

Please make sure that your brokers are really listening on `127.0.0.x` addresses,
or `0.0.0.0` should work if it is a single node cluster.
Also if `advertised.host.name` is configured in kafka, make sure it's resolvable from where brod is running.

**Comment by turtleDeng** [comment]
@zmstone  thanks
