### ISSUE TITLE
Topic creation/partitions

### ISSUE THREAD

**Issue by dgriff1** [kafka4beam/brod#18]
get_metadata will create a topic if it doesn't already exist, but are we missing something about how to create a certain number of partitions on this topic? Producing to a nonzero partition number generates errors. 

Is there a set way to declare a partition and topic as we produce to it?

**Comment by id** [comment]
Kafka does not provide an explicit API to create topics. It will, however, create a topic automatically if a client makes an API call to kafka and the topic specified in the call does not exist. This behaviour is controlled via auto.create.topics.enable parameter (true/false) in broker configuration.

There is also num.partitions parameter in broker config which determines number of partitions for automatically created topics. It's set to 1 by default.

It seems like your Kafka broker is using defaults: auto.create.topics.enable=true and num.partitions=1 (these are kafka defaults, the options don't have to present in server.properties). If you e.g. set auto.create.topics.enable=false in server.properties, Kafka will not create topics automatically. And if you set e.g. num.partitions=42 (while having auto.create.topics.enable=true) new topics created via API calls will have 42 partitions (theoretically, did not test it myself).

Unfortunately, there is no way for a kafka client to control this.

**Comment by id** [comment]
More discussion about this: https://issues.apache.org/jira/browse/KAFKA-2887

**Comment by id** [comment]
And about plans for admin API: https://cwiki.apache.org/confluence/display/KAFKA/KIP-4+-+Command+line+and+centralized+administrative+operations

**Comment by dgriff1** [comment]
That is a very reasonable response. Thank you for creating a great library for us to use.

**Comment by id** [comment]
You are welcome :)
