### ISSUE TITLE
Fetching a message bigger than max_bytes returns undefined instead of retrying with double the size

### ISSUE THREAD

**Issue by Kwisatx** [kafka4beam/brod#180]
Hi,

We stumbled upon an issue related to the max_bytes option.
The expected behavior is that if max_bytes is smaller than one kafka message, we should enter  `handle_message_set(#kafka_message_set{messages = [?incomplete_message]},#state{ max_bytes = MaxBytes} = State0)` in brod_consumer.erl, where we will try to fetch again with the max_bytes * 2.

However, what we've seen is that when pushing a message larger than max_bytes we never enter this case, as the list received is not  [?incomplete_message] but [{kafka_message,65,1,0,<<>>,undefined,2101125231}].

There is a test in the suite that tests this case, but do you have any idea how we could receive undefined instead of incomplete_message?

Our setup is still 1 client producing sync to kafka and one group consumer (maybe I'll have some time this week to set up a test case that reproduces this issue as well as the min_bytes one :p). Currently our config uses {sleep_timeout, 50}, {min_bytes, 1}, {max_wait_time, 50}, but I played around with the values some and we still see the issue.

**Comment by zmstone** [comment]
looking into it.

**Comment by zmstone** [comment]
this looks like a message of size 0.
what's your brod version and kafka version ?

**Comment by Kwisatx** [comment]
I updated to the latest brod (2.2.16) and still have the issue.
However, it looks like it's an issue in kafka 0.10.1.1 and not 0.9.0.1.

**Comment by zmstone** [comment]
it's 0.10.1.0 in trivas.
I will (maybe tomorrow)
1. check if the test case is giving false positive.
2. test it with 0.10.1.1 and 0.10.2.0 tomorrow.

**Comment by Kwisatx** [comment]
We've tested a bit more and we have the error on 0.10.1.0 and 0.10.2.0 as well.

I also ran your test suite on my machine, and t_consumer_max_bytes_too_small does pass, but adding a log in the function shows that we never actually do the doubling (and an erlang:throw is not tripped either ^^).
So it's looking a lot like the test is giving a false positive from what I can tell :)

**Comment by zmstone** [comment]
The test case is indeed giving false positive for kafka 0.10.
I'll investigate further into the protocol details.
I guess it's because brod is using 0.9 protocol talking to kafka,
then kafka has to downgrade the mesage format in memory before sending to brod.
this downgrade might have discarded the incomplete `value` field.

we did not notice this in our production even though we are running kafka 0.10
because we configured kafka brokers to store 0.9 message format on disk.

**Comment by zmstone** [comment]
@Kwisatx I know how to fix it. Thanks for reporting this!
Will work on a pr soon.

**Comment by zmstone** [comment]
@Kwisatx it should have been fixed in latest master.
this bug forced us to bump version to 2.3 earlier than expected :)

**Comment by zmstone** [comment]
tagged 2.3.1
thanks again for the awesome tests.

**Comment by Kwisatx** [comment]
Yep, it's all looking good :).
Thanks for the fix!
