### ISSUE TITLE
Lack of timeouts in receive can block producers 

### ISSUE THREAD

**Issue by eriklee** [kafka4beam/brod#187]
We've had a few cases where some of our producers get stuck waiting for messages in the produce function. I'm still not sure what the processes they were waiting for responses from were doing, but it corresponds to problems with our kafka cluster. Even once the kafka cluster is fully operational again these processes still seem to be stuck.

Sorry for the relatively unhelpful report, but it seems like there needs to be some sort of timeout behavior here to ensure that a misbehaving producer can't kill an entire node.

**Comment by zmstone** [comment]
Hi @eriklee 
Which brod version are you running ?
There is timeout by default 4 minutes. i.e. whatever request sent to kafka, if there is no response received for up to 4 minutes (configurable), brod_sock process will exit itself.
Then the producer process should notice and retry the batches.

**Comment by zmstone** [comment]
timeout was added to 2.2.13: #163

**Comment by eriklee** [comment]
Ah, we're running a version from October. I'll give the latest version a try, thanks!
