### ISSUE TITLE
Producer leader caching

### ISSUE THREAD

**Issue by dgriff1** [kafka4beam/brod#19]
The way brod producer caches leaders leads to creating way too many sockets. 

The Producer creates a proplist of [{{Topic, Partition}, brod_sock Pid} | Leaders ]

For a fairly typical case of having say 10 topics with 15 partitions each you would create 150 socket connections. Even if you have a typical 3 node kafka this ends up being 50 connections to each kafka. 

We discovered this through testing brod producing to this setup
- single kafka
- 1 topic
- 11 partitions
- 10 poolboy workers each with a producer

After messing with our worker size we discovered that we can easily flood kafka with connections .  After adding some debug to brod we saw that we are creating 11 sockets per producer when 1 would do. 

Any thoughts?

**Comment by zmstone** [comment]
please take a look at the 2.0-dev branch.
we are rewriting connection management parts.
the idea is to introduce a 'client' concept, one client should only establish one tcp connection to a broker.

it is completely flexible for the users how they want to group the producers/consumers to any number of clients.

**Comment by dgriff1** [comment]
Will that fix this issue? Oddly, the consumer seems to do a great job of determining the broker from the metadata.

**Comment by zmstone** [comment]
in the current implementation, each producer will have to establish connections to all partition leaders it produces data to.
meaning, if you have N producer processes, and M different leaders, there will be a need of N \* M connections.
I'm not sure why you observed different behavior in consumers, but it's essentially the same logic.

in 2.0, if you start one client per poolboy worker, the number of required socket will be the same, but this is really a bad practice.
we would recommend to start one client for all your poolboy workers, or there is probably no need for poolboy anymore, because under the supervisor tree, producers are spawned per topic-partition anyway.

**Comment by dgriff1** [comment]
The problem is that the producer leader caching is flipped. Instead of saying "Do we have a connection to broker X?" it determines "Do we have a connection for topic T and partition P?"  which will mean you end up duplicate connections all over unless I am really misunderstanding. 

If you wanted to reproduce look at the leader caching in brod_producer then write a test case which will produce to a bunch of partitions on the same broker.

**Comment by zmstone** [comment]
Perhaps i didn't make it clear,
trying again: you are completely right about the fact that current implementation abuses the socket usage.

And this one of the main issues we wanted to fix in 2.0. (however even in 2.x, if you start your clients wrong, you'll end up in the same situation).

I'm not sure if we want to fix this for 1.x, @id  what do you think ?

**Comment by dgriff1** [comment]
We are sharing a single producer now and the issue is manageable. If it's an easy fix it would be nice for 1.x, everything else works great and we are getting huge throughput.

**Comment by id** [comment]
@zmstone not sure if it does worth it, I'd rather concentrate on getting 2.0 ready

@dgriff1 have you tried to run the same setup but without poolboy? Just calling brod:produce directly?

**Comment by dgriff1** [comment]
@id, yes we wrote a test outside of poolboy that just creates a produce and produces to a bunch of different partitions.  If you add debug around here: https://github.com/klarna/brod/blob/master/src/brod_producer.erl#L265 you can see that you are creating a ton of brod_socks to the same broker.

**Comment by id** [comment]
In the same process?

**Comment by dgriff1** [comment]
Yes, 1 producer keeps trying to find leaders and keeps creating more sockets to those leaders but they are all the same leader.

**Comment by id** [comment]
Right. It is solved in 2.x but we definitely could do smarter in the first place.
Will try to fix this over the weekend, should be simple enough.
