### ISSUE TITLE
Handle earliest begin_offset in group member/subscriber

### ISSUE THREAD

**Issue by objectuser** [kafka4beam/brod#191]
Based on your advice [here](#179) I implemented the `brod_group_member` behavior with a subscriber per partition. I tried to follow Brucke as suggested.

This allowed me to handle the `assignments_received` callback and get correct balancing between two consumers. (It also gave us a substantial increase in throughput.) Thank you very much for that recommendation!

One thing I've noticed is that I'm not handling offsets correctly. I would like to specify `begin_offset` as `earliest` when my subscriber starts consuming from a topic. But on subsequent starts, I would like it to pick up where it left off with respect to the consumer group.

So far, I can't seem to get a combination that does that using various combinations options to:

1. `:brod.start_client`
2. `:brod.start_consumer`
3. `:brod_group_coordinator.start_link`
4. `:brod.subscribe`

If it helps, I'm acknowledging offsets with:

```elixir
    :ok = :brod.consume_ack(subscriber_pid, offset)
    :ok = :brod_group_coordinator.ack(group_coordinator_pid, gen_id, topic, partition, offset)
```

Any advice would be appreciated!

**Comment by zmstone** [comment]
`brod_consumer` does not fetch any message until there is a subscriber.
And it stops fetching messages when the subscriber process is down (it monitors the subscriber pid).
So you could just use whatever `:begin_offset` in the third argument of`:brod.subscribe/3`.

In your specific case, the assignment is a `brod_received_assignment` record,
the `begin_offset` field in this record should be used in the `:brod.subscribe/3` call
If the received `begin_offset` is `:undefined`, then you can use
`{:begin_offset, :earliest}` in the option list.

**Comment by zmstone** [comment]
Hope it wont add confusion: `:brod.start_consumer` accepts `{:begin_offset, ...}` in the consumer config, this begin offset works like a default option, if there is no `:begin_offset` given in `:brod.subscribe` call, the one in config is used.
You could just always use a `begin_offset` option in `:brod.subscribe` call to make it less confusing.

As for acking, `brod.consume_ack` only tells `brod_consumer` to fetch more messages (when pre-fetch-count allows), it's the `:brod_group_coordinator.ack` call that should eventually get your offsets committed to kafka.

**Comment by objectuser** [comment]
@zmstone Thank you! That works perfectly. I was actually ignoring the offset from `brod_received_assignment` and I don't know why. 😕 

> As for acking, brod.consume_ack only tells brod_consumer to fetch more messages (when pre-fetch-count allows), it's the :brod_group_coordinator.ack call that should eventually get your offsets committed to kafka.

👍 Understood. There's a nice comment in Brucke to that effect:

```erlang
      %% tell upstream consumer to fetch more
      ok = brod:consume_ack(ConsumerPid, OffsetToAck),
```

Thanks again for all of your help!
