### ISSUE TITLE
Support for Message Timestamp

### ISSUE THREAD

**Issue by objectuser** [kafka4beam/brod#205]
Is the Kafka [message timestamp field](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol) something Brod could expose in the [message record](https://github.com/klarna/brod/blob/master/include/brod.hrl#L33)?

From the docs, it's hard to understand if this is actually part of the protocol at this point (it refers to 0.10.0) or something that's not there yet.

Thanks!

**Comment by zmstone** [comment]
timestamp is added to version 1 fetch response.
brod supports only version 0 so far.
full support for kafka 0.10 protocol is a work-in-progress

**Comment by objectuser** [comment]
@zmstone OK, glad to hear it's something you're interested in. 👍 

Is there an issue or branch I can watch for that?

**Comment by zmstone** [comment]
We don't have an issue or PR to track this.
Likely there will be more than one PR because it's a pretty big change.
You may keep this issue open, we'll update/close it when it's ready

**Comment by objectuser** [comment]
That makes complete sense. Thanks very much!

**Comment by zmstone** [comment]
just an update.
`ts` and `ts_type` has been added to `#kafka_message{}` record in latest master (3.0.0).
However, fetch request version is still hard-coded to 0. meaning both fields will always be `undefined` for now.
Planing to work on a 3.1 which should pick the API versions depending on a query result.

**Comment by objectuser** [comment]
@zmstone Exciting! Thanks for the update!

**Comment by vputrevu** [comment]
Any ETA on full support for 0.10 or 0.11 version? Thanks in advance!

**Comment by zmstone** [comment]
@vputrevu sorry for the late reply. I've started working on it, but no ETA because this is now sort of a spare-time priority for this feature.
