### ISSUE TITLE
Incorrect last commited offset.

### ISSUE THREAD

**Issue by kansi** [kafka4beam/brod#212]
Hi, I am trying to publish messages to kafka and process them on demand rather than subscribing and continously receiving messages. Till now I have managed the following

- `brod:start_client`
- `brod:start_producer`
- `brod:produce_sync` : publish messages

The above works fine. Then I try to get the last commited offset for the partition I published to using `brod:get_offsets` but it always returns the offset of the lastest message that I published. So my question is how do I get the last commited offset and how to I read the message from a particular partition (`brod:fetch` ?) and ack it later (`brod:consume_ack`?).

**Comment by id** [comment]
Hi @kansi .

You can only commit offsets to Kafka if you use consumer groups and receive messages continuously. Meaning, standard brod api for consumers.

It is possible to do what you want, but for this you need to use a custom offset storage, e.g. a file or a database.

Code to get message at the latest offset may look like this:
```
{ok, Pid} = brod_client:get_leader_connection(brod_client_id, Topic, Partition),
{ok, [Offset]} = brod_utils:fetch_offsets(Pid, Topic, Partition, latest, 1),
ReqFun =
    fun(MaxBytes) ->
        kpro:fetch_request(Topic, Partition, Offset, _MaxWaitTime = 30000, _MinBytes = 0, MaxBytes)
    end,
{ok, [#kafka_message{} = Msg]} = brod_utils:fetch(Pid, ReqFun, _MaxBytes = 1024000, Offset).
```

**Comment by zmstone** [comment]
* `brod:get_offsets` is to resolve -1 (latest) -2 (earliest) (or a timestamp) to kafka offset.
* `brod:fetch` is used primarily in `brod-cli`. not recommended for regular Eralng applications to use
* `brod:consume_ack` is used by subscriber to tell `brod_consumer` that the message has been consumed, and it's time to fetch/poll more messages from Kafka
* To commit offsets to kafka, you should use a consumer group
* You can also commit/persist offsets locally by the message-set subscriber, then provide `{begin_offset, CommittedOffset + 1}` in consumer config for `brod:start_consumer`

**Comment by kansi** [comment]
@id I tried exectuing what you suggested i.e.

```
{ok, Pid} = brod_client:get_leader_connection(brod_client_id, Topic, Partition),
{ok, [Offset]} = brod_utils:fetch_offsets(Pid, Topic, Partition, latest, 1).
```
But it still returns the offset of the lastest published message rather than the last commited offset. In contrast if I try to use consumer groups it gets the correct offset but then I have no control of which partitions I choose to read from and I also cannot fetch messages on demand. 

@zmstone could you suggest how I can specify which partitions to read from when creating a consumer group ? If that is not possbile directly (which I think is the case) could you point to the code that tries to get the partitions and alocated them to the group members.

**Comment by id** [comment]
@kansi if you want to get last committed offset (when using Kafka as offsets storage), you have to subscribe to _consumer_offsets topic, receive and parse messages manually, and record in your app state offset for your consumer group.

Kafka's consumer groups are not designed for the use case you described. It will be a lot of work to get it working.

**Comment by zmstone** [comment]
First of all, `brod_utils:fetch_offsets` is `brod:get_offsets` equivalent,
it is to resolve semantic offset (latest | earliest etc) or timestamp to real kafka offsets.
It has nothing to do with consumer group committed offsets.

There is NO API to fetch consumer group committed offsets.
The committed offsets fetch request is only implemented as a part of the consumer
group membership management protocol.

Currently brod only supports 'roudrobin' partition assignment strategy.
i.e. Consumer group leader assigns partitions evenly across all members.
e.g. if consumer 1 and 2 both subscribe to the same topic having N partitions,
when both members are active (the group is balanced), the even/odd partitions
will be assigned alternatively to each member.

2 ways to control partition assignments:
* Use `{partition_assignment_strategy, callback_implemented}` in group config, and implement `assign_partitions/3` callback.
* Implement the `brod_group_member` behaviour to have your own partition assignment strategy.
[brucke](https://github.com/klarna/brucke) is another group member behavior implementation example 

Nonetheless, if you just want a place to store the consumed offsets,
(but not to have a different assignment strategy)
you can always use only one consumer in a group (make a unique group-ID),
then the topic (all partitions) will be always assigned to the same subscriber.

**Comment by zmstone** [comment]
not an issue.
consumer should either track last offsets by themselves or use consumer group.
