### ISSUE TITLE
a new LO_CMD_SUBSCRIBE_PARTITIONS interval is added every new_assignment in brod_group_subscriber

### ISSUE THREAD

**Issue by mokele** [kafka4beam/brod#214]
for every partition reassignment `{new_assignments ...}` an extra `?LO_CMD_SUBSCRIBE_PARTITIONS` info message is added to the message queue of the running group subscriber, causing a additional resubscribe interval every 2000ms due to `handle_info(?LO_CMD_SUBSCRIBE_PARTITIONS, ...)` always recursively resending back to self.

First allocation: 1 resubscribe attempt every 2s
Second allocation: 2 resubscribe attempts every 2s
Third allocation: 3 resubscribe attempts every 2s
etc...

**Comment by zmstone** [comment]
@mokele Thanks for reporting this. I am working on a fix.

**Comment by zmstone** [comment]
included as a part of 2.5.0 release.
published to hex.
