### ISSUE TITLE
Committed offsets are being ignored by the group coordinator when the offset value is 0

### ISSUE THREAD

**Issue by jesuspc** [kafka4beam/brod#222]
Steps to reproduce:

- Create a new topic with multiple partitions.
- Create a subscriber group using brod:start_link_group_subscriber pointing to that topic. The group config that I used was [{:offset_commit_policy, :commit_to_kafka_v2}, {:offset_commit_interval_seconds, 5}].
- In the handle_message callback of the callback module use brod_group_subscriber::ack to ack the messages as processed. The acks will be committed after 5 seconds as per the config above. 
- Produce a couple of messages to kafka, wait for the commit from the subscriber to be sent.
- Stop the application.
- Restart the application. The messages will be received again if the offset assigned to the consumer group for their partition is 0. 

I have traced back the issue to [this line](https://github.com/klarna/brod/blob/master/src/brod_group_coordinator.erl#L924). Removing the second condition that checks wether the offset is bigger than 0 fixes the problem. Even though that piece of code seems intentional, so I am wondering why was it added there in the first place.

**Comment by zmstone** [comment]
@jesuspc I believe that's a bug, should be `>= 0`
