### ISSUE TITLE
record kafka_message already defined

### ISSUE THREAD

**Issue by liang0-0** [kafka4beam/brod#224]
env:
    Centos7 
Linux 10-205-40-77 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
    kafka_protocol: master
    brod: master

I'm developing a emq kafka plugin with erlang , and my project  use brod and kafka_protocol dependency, 
In the kafka_protocol project, it has define a record named [kafka_message](https://github.com/klarna/kafka_protocol/blob/master/include/kpro_public.hrl).
and in brod , 
brod also have a record named [kafka_message](https://github.com/klarna/brod/blob/master/include/brod.hrl)

when I use both of them, this will cause a problem in compile time, ``` record kafka_message already defined.```

I have tried a way to fix that, bug failed!
1). I forked the brod project, add the ifndef, but  not worked.
```erlang
-ifndef(KPRO_PUBLIC_HRL_).
-define(KPRO_PUBLIC_HRL_, true).

%% For applications on top of kafka client (brod).

-record(kafka_message,
        { offset :: kpro:offset()
        , magic_byte :: kpro:int8()
        , attributes :: kpro:int8()
        , key :: kpro:bytes()
        , value :: kpro:bytes()
        , crc :: non_neg_integer() %% not kpro:int32() because it's unsigned
        , ts_type :: kpro:timestamp_type()
        , ts :: kpro:int64()
        }).

-endif.
```

and the exception message show that:
```
 ERLC   brod.erl brod_auth_backend.erl brod_cli.erl brod_cli_pipe.erl brod_client.erl brod_consumer.erl brod_consumers_sup.erl brod_group_coordinator.erl brod_group_member.erl brod_group_subscriber.erl brod_kafka_requests.erl brod_producer.erl brod_producer_buffer.erl brod_producers_sup.erl brod_sock.erl brod_sup.erl brod_topic_subscriber.erl brod_utils.erl
src/brod.erl:504: argument mismatch for macro 'incomplete_message'
src/brod.erl:471: type kpro_MetadataResponse() undefined
```
the brod is compiled after kafka_protocol.

Can anybody give me some idea to solve this problem, Very thanks.

**Comment by id** [comment]
Hi @liang0-0, https://github.com/klarna/brod/pull/219 should solve it.

We hope to have it ready soon.

**Comment by zmstone** [comment]
make sure kafka_protocol is resolved from brod's dependency.
for example, brod 2.x should use kakfa_protocol 0.9

kafka_protocl 1.0 (current master branch) is to be used by brod 3.0
