### ISSUE TITLE
Unable to publish to docker hosted kafka

### ISSUE THREAD

**Issue by vedavidhbudimuri** [kafka4beam/brod#226]
Im using kafka 0.11.0
I have set kafka endpoints as below
KafkaBootstrapEndpoints = [{"10.5.0.8", 9092}].
`11> ok = brod:produce_sync(client1, Topic, Partition, <<"key1">>, <<"value1">>).`
Output: 
=ERROR REPORT==== 29-Aug-2017::14:55:31 ===
client client1 failed to connect to 0.0.0.0:9092
reason:{connection_failure,econnrefused}
=WARNING REPORT==== 29-Aug-2017::14:55:31 ===
Failed to (re)init socket, reason:
{connection_failure,econnrefused}
=ERROR REPORT==== 29-Aug-2017::14:55:32 ===
client1 (re)connect to 0.0.0.0:9092 aborted, last failure reason:{connection_failure,
                                                                  econnrefused}
=WARNING REPORT==== 29-Aug-2017::14:55:32 ===
Failed to (re)init socket, reason:
{connection_failure,econnrefused}
=ERROR REPORT==== 29-Aug-2017::14:55:32 ===
client client1 failed to connect to 0.0.0.0:9092
reason:{connection_failure,econnrefused}
=WARNING REPORT==== 29-Aug-2017::14:55:32 ===
Failed to (re)init socket, reason:
{connection_failure,econnrefused}
=ERROR REPORT==== 29-Aug-2017::14:55:33 ===
client1 (re)connect to 0.0.0.0:9092 aborted, last failure reason:{connection_failure,
                                                                  econnrefused}

**Comment by id** [comment]
@vedavidhbudimuri try to run kafka with `advertised.listeners=PLAINTEXT://127.0.0.1:9092` in server.properties.

**Comment by vedavidhbudimuri** [comment]
Sorry, my bad
the issues is that I have set listener in server.properties for kafka node to 0.0.0.0
