### ISSUE TITLE
Many report log after upgrading to 3.0

### ISSUE THREAD

**Issue by nemzsom** [kafka4beam/brod#227]
Hi!
After upgrading to version 3.0.0 I started receiving many-many logs about supervisors like this:
```
=PROGRESS REPORT==== 30-Aug-2017::18:27:40 ===
          supervisor: {local,'Elixir.LI.Indexer.Pipeline.Supervisor'}
             started: [{pid,<0.357.0>},
                       {id,'Elixir.LI.Indexer.Pipeline.Stages.Fetcher'},
                       {mfargs,
                           {'Elixir.LI.Indexer.Pipeline.Stages.Fetcher',
                               start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,5000},
                       {child_type,worker}]
```
I use brod in Elixir and it seems I cannot turn off these logs. They appear on the standard out.
It doesn't happen on the 2.* versions.
Is it a bug or there is some config parameter for turn this logging off?

Thank you,
Zsombor

**Comment by id** [comment]
But these are not related to brod in any way.

**Comment by nemzsom** [comment]
I know, this particular log is not related to brod. I receive these reports for all supervisors, also for brod supervisors.
And they started to appear after I upgraded to 3.0.0. If I downgrade they disappear again.
So maybe this is caused by some dependency for 3.0.0. 
I don't know but it is clearly related to brod as I don't change any config just the brod version and I starting to receive these logs. I tried to debug the cause but failed so far as I'm new to Elixir and Erlang.

An example log for a brod supervisor:
```
=PROGRESS REPORT==== 30-Aug-2017::17:23:17 ===
          supervisor: {local,brod_sup}
             started: [{pid,<0.609.0>},
                       {name,kafka_client},
                       {mfargs,
                           {brod_client,start_link,
                               [[{"localhost",9092}],
                                kafka_client,
                                [{endpoints,[{"localhost",9092}]},
                                 {auto_start_producers,true}]]}},
                       {restart_type,{permanent,10}},
                       {shutdown,5000},
                       {child_type,worker}]
```
I just inserted a different log first to show I get these reports for all supervisors.

**Comment by id** [comment]
Ok, then it might be because supervisor fails to start a child and keeps retrying.
I see that at least 3rd argument to `brod_client:start_link/3` is wrong.

Can you show the code where you start brod and config for the application related to brod?

**Comment by nemzsom** [comment]
I created a dummy project to illustrate the issue: https://github.com/nemzsom/brod_3_logging_issue
It has brod as the only dependency and it doesn't even start brod. It doesn't do anything but if it is started it prints out these reports to the standard out. If using brod 2.5.0 it prints out nothing which is the expected behaviour.
I'm using Elixir 1.5.1 if its related:
```
$ elixir -v
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.5.1
``` 
I hope this helps!

**Comment by nemzsom** [comment]
Oh, I found the solution.
If you insert this into `config.exs`:
```config :sasl, sasl_error_logger: false```
Then these reports go away. So I think this is cause by the `sasl` dependency in brod. While this is not really a bug, maybe worth mentioning how to disable these reports somewhere in the documentation.

**Comment by id** [comment]
Right, we've added sasl in the list of applications that brod requires. Don't remember why.

Thanks for the report, we will discuss what we are going to do with it. So far I think we can revert this change.

ping @zmstone

**Comment by zmstone** [comment]
agree to remove
