### ISSUE TITLE
error when make.

### ISSUE THREAD

**Issue by buxizhizhoum** [kafka4beam/brod#230]
There are errors when make it, is any idea about it?
erlang.mk:5074: warning: overriding commands for target `/home/uuu/brod/deps/docopt'
erlang.mk:5049: warning: ignoring old commands for target `/home/uuu/brod/deps/docopt'
erlang.mk:5074: warning: overriding commands for target `/home/uuu/brod/deps/jsone'
erlang.mk:5049: warning: ignoring old commands for target `/home/uuu/brod/deps/jsone'
make[1]: Entering directory `/home/uuu/brod/deps/supervisor3'
 ERLC   supervisor3.erl
src/supervisor3.erl:200: syntax error before: '::'
src/supervisor3.erl:208: syntax error before: '::'
make[2]: *** [ebin/supervisor3.app] Error 1
make[1]: *** [app] Error 2
make[1]: Leaving directory `/home/uuu/brod/deps/supervisor3'
make: *** [deps] Error 2

it raise error on centos 6.8, but could work on my laptop with ubuntu 16.04.
Thanks in advance!

**Comment by zmstone** [comment]
@buxizhizhoum your OTP in centos6 is probably too old (R16?).
check version: `erl -noshell -eval "io:put_chars(erlang:system_info(otp_release)), halt(0)"`

**Comment by buxizhizhoum** [comment]
It is R14, I will try to update it and have a try after that, thanks a lot!
