### ISSUE TITLE
Documentation on best practice for reconnect when kafka connections are lost

### ISSUE THREAD

**Issue by meadoch1** [kafka4beam/brod#235]
We are using Brod in our application and have been seeking how to best set up our application to handle network interruptions and the like that make it lose it's connection to Kafka.  Are there guidelines or examples you can point out as to how brod in intended to handle these situations?

Thanks

**Comment by zmstone** [comment]
If your clients are started on demand (not in sys.config in for `brod` application),
you should link or monitor it, then restart the producers or consumers for that client after a client restart.
apart from that, `supervisor3` should take care of retries.

**Comment by meadoch1** [comment]
I have tried both on demand and using sys.config for the `brod` application.  It appears that if the connection is gone for more than a trivial number of seconds, the retries of the supervisor are exhausted and it doesn't attempt to reconnect anymore.  

Additionally, is there a callback if I'm using the sys.config to know when a connect/reconnect is successful so that I can then start consumers and producers?  If not, is that usually done through a supervisory tree with :rest_for_one?

**Comment by zmstone** [comment]
Which version did you test?

Client restarts should never exhaust supervisor.
All supervisors in brod are implemented using supervisor3. All children are started with delay retry spec.

However, if a client restarts (when the whole cluster is not reachable), all consumers and producers linked to it will disappear and need to be restared unless they are also in sys.config

One client only establishs one metadata connection, all payload connections are stared when needed. Meaning brod_producer won’t try connect unless there is a produce request. brod_consumer won’t connect if there is no subscriber.

**Comment by zmstone** [comment]
There is no callback to notify client readiness. I guss the simplest approach is to let brod take care of restarts, and the caller performs delay + retry to produce or subscribe.
You can also manage client under your own supervision tree, but what restart strategy to choose depends a lot on use case.

**Comment by meadoch1** [comment]
That makes sense.  Is there an example of setting up the consumers & producers in sys.config?  I looked but only found the client setup.  If listing those in sys.config gives brod all it needs to do the work that sounds great.

**Comment by zmstone** [comment]
Sorry, I remembered it wrong.
We had idea to put producer and consumer configs in sys.config, but not yet implemented.
Currently there is only `auto_start_producer` you can use for producers.
I'll work on it.

In the mean time you can put `brod:start_producer` / `brod:start_consumer` to your `init` function.
and link or monitor the client pid to restart the caller if client dies.

**Comment by meadoch1** [comment]
Thanks.  That was my plan.

And thank you for your quick responses.
