### ISSUE TITLE
badarg for brod_topic_subscriber:start_link

### ISSUE THREAD

**Issue by rounakdatta** [kafka4beam/brod#239]
While testing the **Quick Demo**, I'm stuck at the 12th command. Please help me sort out this issue.

- Zookeeper, Kafka running; with the latter running at localhost:9092.

- brod-test topic exists.

- Producer part of brod is working fine (I'm able to consume the messages through the native Kafka consumer).

- This consumer part of brod isn't working fine for me.

>>**brod_topic_subscriber:start_link(client1, Topic, Partitions=[Partition],
                                   _ConsumerConfig=[{begin_offset, earliest}],
                                   _CommittdOffsets=[], SubscriberCallbackFun,
                                   _CallbackState=self()).**

_** exception exit: badarg
     in function  apply/3
        called as apply(#Fun<erl_eval.18.99386804>,init,[])
     in call from brod_topic_subscriber:init/1 (src/brod_topic_subscriber.erl, line 178)
     in call from gen_server:init_it/2 (gen_server.erl, line 365)
     in call from gen_server:init_it/6 (gen_server.erl, line 333)
     in call from proc_lib:init_p_do_apply/3 (proc_lib.erl, line 247)_

I am sure that I haven't done any modifications to the original code. Can this be some syntax error? Please help me sort this issue out.

**Comment by zmstone** [comment]
Sorry, the demo code is a bit outdated, please add a ‘message‘ or ‘ message_set’ atom before the SubscriberCallbackFun in the arg list.
Will fix it.

**Comment by rounakdatta** [comment]
Thanks, I'm now able to consume messages through brod.
Thanks again for the prompt support.
