### ISSUE TITLE
Constant lag of one message on every partition

### ISSUE THREAD

**Issue by nemzsom** [kafka4beam/brod#241]
Hi!
I noticed that the `kafka-consumer-groups.sh` reports a one message lag for every partition when using a brod consumer.
`kafka-consumer-groups.sh --new-consumer --bootstrap-server kafkahost:9092 --describe --group my_consumer_group` reports

GROUP | TOPIC | PARTITION | CURRENT-OFFSET | LOG-END-OFFSET | LAG | OWNER
--------|--------|------------|--------------------|--------------------|------|--------
my_consumer_group | test_topic | 0 | 3 | 4 | 1 |nonode@nohost/<0.1036.0>_/172.26.0.1

with one partition but if the topic has more partition the lag is one for each.

I believe the committed offset does not follow the kafka consumer documentation at https://kafka.apache.org/0110/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html

> Note: The committed offset should always be the offset of the next message that your application will read. Thus, when calling commitSync(offsets) you should add one to the offset of the last message processed. 

I think brod doesn't add one when committing but at the same time when the consumer starts it adds one to received offset from kafka so it works good and don't skip messages.

This issue doesn't create incorrect behaviour, however we use a lag monitoring tool and only the brod consumer reports a constant lag. Other clients (java, scala) follow the kafka consumer recommendation.

Could you confirm my theory and maybe fix this if you agree?

**Comment by zmstone** [comment]
Yes, brod commits what's consumed, not what's to fetch next.
The doc wasn't this clear when we started, and I did not revisit this doc.
Thanks for reporting this. We'll have it fixed soon.
