### ISSUE TITLE
brod-poolboy integration

### ISSUE THREAD

**Issue by rounakdatta** [kafka4beam/brod#243]
Well, I'm building a service which uses **brod** as the producer as well as consumer client for **Kafka** message broker. And I'm trying to handle the worker processes through **[poolboy](https://github.com/devinus/poolboy)**.
Now I'm stuck at where to call poolboy (in brod) to pass the messages (from the producer on the other side) and then get the response from poolboy to brod.

I understand how poolboy works, but ain't sure how to pass the request from brod to poolboy. Please note that I'm able to pass requests to poolboy explicitly (through commands), but I need to get it done through brod (so that it doesn't have to publish messages manually using commands for each operation). This is being done as a part of a microservice backend project.

How do I accomplish this? Do I need to change the brod source codes? Or I need a separate handler?Thanks!

**Comment by zmstone** [comment]
Hi @rounakdatta 
__brod__ produce  requests are sent to `brod_producer` as messages
and the produce reply (e.g. ack) are sent back to caller as messages.
So I'm not quite sure what you mean by "call poolboy (in brod)".

__brod__ workers are spawned and managed by its supervisor one for each partition,
if you want to by-pass supervisor and spawn and manage the workers from __poolboy__,
you'll have to implement two `brod_client` APIs yourself:
`brod_client:get_leader_connection(ClientPid, Topic, Partition)`
and
`brod_client:register_producer(ClientPid, Topic, Partition)`

**Comment by rounakdatta** [comment]
I'm now able to process the messages (making basic print statements, passing the messages to poolboy) within **brod_topic_subscriber:handle_messages/3** [Line 360]. Now can you please help me confirm/clarify whether the messages are being handled parallely (through worker processes) or sequentially? 
Say if 4 messages have been posted under a particular topic and to a particular partition, and then how they are processed (parallely or sequentially)?

If it's done sequentially, isn't it a bottleneck?

Thanks a lot for the expert guidance!

**Comment by zmstone** [comment]
Messages from a partition are fetched in async-ly from kafka with a configurable fetch-ahead window size.
Then messages from different partitions in the same topic are all sent to `brod_topic_subscriber`,
in this sense, all messages are processed sequentially in topic subscriber.

To achieve bset parallelization, a partition subscriber should be implemented outside of `brod`.

Inside the partition subscriber, in case message order is not important,
messages can be sent to a pool of workers (e.g. in poolboy)
