### ISSUE TITLE
Brod 3.3.3 (Protocol 1.1.1) Unable to Consume

### ISSUE THREAD

**Issue by rawkode** [kafka4beam/brod#247]
Hi,

I've found an issue where new consumer groups are unable to consume, even though the `begin_offset=1` and it's `elected=true`

I initially thought this was an issue with `Kaffe`, but downgrading `brod` and `kafka_protocol` fixed the problem.

Logs can be found in this issue:
https://github.com/spreedly/kaffe/issues/48

**Comment by zmstone** [comment]
Hi  @rawkode .
I have also commented here: spreedly/kaffe#48.
Just to be sure that I did not miss anything:
The problem was that `offset = -1` received from assignment was interpreted as `latest` by brod
and it caused your consumer to behave different than brod before version `3.3.3`

**Comment by rawkode** [comment]
OK. Thanks @zmstone

Just to clarify, is the fix to happen in brod or Kaffe?

**Comment by zmstone** [comment]
I am going to revert the special handling of `offset = -1` in `brod` so there is no change needed in `kaffe`.

> The problem was that offset = -1 received from assignment was interpreted as latest by brod
and it caused your consumer to behave different than brod before version 3.3.3

@rawkode  I was actually expecting you to comment if this is all, or if I have missed anything.

**Comment by zmstone** [comment]
well. published to hex.
if there is anything else please create another issue.

**Comment by rawkode** [comment]
Thank you for your prompt response, @zmstone - super helpful.

Appreciated
