### ISSUE TITLE
brod_producer exit 'MessageTooLarge'

### ISSUE THREAD

**Issue by ForLina** [kafka4beam/brod#249]
brod version :3.3.4
kafka_prorocol version: 1.1.1

error msg
17:08:24.068 [error] gen_server <0.1771.0> terminated with reason: {not_retriable,{produce_response_error,<<"mqtt_dev2">>,1,-1,'MessageTooLarge'}} in brod_producer:handle_info/2 line 317

This problem only happens when massive messages being pushed to kafka (about 100k/s).
And I wonder this error was caused by kafka or brod? I know this error is return from kafka, but what causes this ? Brod pack message error or Kafka unpack error？

**Comment by zmstone** [comment]
what's the max message allowed by kakfa ? (look for `max.message.bytes` in server.properties).
If it is a single message being too large, there is nothing we can tune in `brod`.
If it is a compressed batch being too large, try use a smaller `max_batch_size` in producer config.

**Comment by ForLina** [comment]
The dafault max_batch_size of kafka is 100012, and I changed max_batch_size of brod producer to 900000, then it's ok now. Thanks a lot.
