### ISSUE TITLE
Clarification Request for brod:fetch

### ISSUE THREAD

**Issue by randysecrist** [kafka4beam/brod#251]
See attached screen shot ...

![screen shot 2017-12-12 at 3 21 34 pm](https://user-images.githubusercontent.com/141339/33911782-a8401dd6-df50-11e7-9b09-9e08d2a73d94.png)

brod:fetch using the earliest offset only seems to be returning a subset of messages.

In this case, There are 5 messages in partition 0.  Earliest offset is 0, latest is 5.  A call to fetch using offset 0 returns message 0,1 and 2.  Calling fetch with offset 3 returns the last two messages.

Is this expected?  Anyway to get back all 5 with a single fetch call?

**Comment by zmstone** [comment]
Which brod version and which kafka version were you testing?
on latest version `3.3.4`
`:brod.fetch/3` by default uses 100K Bytes as `max_bytes` in fetch request.
`:brod.fetch/8` allows you to specify `max_bytes`.

However, the messages are not that big, i.e. 3 messages are obviously less than 100K.
This seem quite odd to me. Not sure why kafka would not return all 5 messages in the batch.

**Comment by zmstone** [comment]
there are 40 hours between timestamp of message at offset 2 and offset 3,
maybe the are from two segments in kafka

could you check in kafka log-data directory, see if there are two segments for that partition ?

**Comment by randysecrist** [comment]
Yes, I had to find another partition and offset that was doing this; but it looks like there are multiple segments.

![screen shot 2017-12-13 at 9 28 23 am](https://user-images.githubusercontent.com/141339/33949879-17067f5c-dfe8-11e7-9b0e-6fadcd8946a8.png)

We use kafka 2.11.  Brod; 3.3.4

**Comment by zmstone** [comment]
that should be it.

**Comment by randysecrist** [comment]
Ok, so it is expected.  The code I have doing the fetch looks like this; does this seem correct?

```elixir
  defp fetch(acc, hosts, topic, partition, start, total_count) do
    case :brod.fetch(default_hosts(), topic, partition, start) do
      {:ok, []} -> acc
      {:error, reason} -> {:error, reason}
      {_, messages} ->
        result = acc ++ messages
        case (length(result) < total_count) do
          true -> fetch(result, hosts, topic, partition, start + length(result), total_count)
          false -> result
        end
    end
  end
```

**Comment by zmstone** [comment]
Seem correct. But it’s probably better to connect leader then use brod_util:fetch/4 to avoid re-connect for each attempt.
See brod_cli fetch for example

**Comment by randysecrist** [comment]
Thank you for the review.

**Comment by zmstone** [comment]
Should be start+length(messages) not length(result)
Also next begin offset is not always start+length because offsets may not sequential in compacted partitions, should be last message’s offset+1
