### ISSUE TITLE
offsets in compressed messages batch

### ISSUE THREAD

**Issue by bosak** [kafka4beam/brod#252]
Hi, 
can you please help and point me some direction, what am I doing wrong (hopefully settings of kafka itself). When I try to add **compression: :gzip** to producer config, I get :CorruptMessage. Same is happening for brod-cli trying to pipe README.md as in examples. 
I am using bulk producer api with 3-tuples {timestamp, key, value}.

'''
Last message: {:msg, #PID<0.920.0>, {:kpro_rsp, :produce_response, 2, 3, [responses: [[topic: "USER_LOGIN_1", partition_responses: [[partition: 0, error_code: :CorruptMessage, base_offset: -1, log_append_time: -1]]]], throttle_time_ms: 0]}}
'''
It may be worth to have some example/doc about using compression.
Thanks a lot :).

**Comment by zmstone** [comment]
@bosak kafka version ? and brod version ?

**Comment by zmstone** [comment]
never mind, found the issue. will fix soon.

**Comment by zmstone** [comment]
https://github.com/klarna/kafka_protocol/pull/39
@bosak I ran some tests for this ^, should work,
but could you pull the changes in and help to verify it? (only need `kpro.erl`)

**Comment by bosak** [comment]
Hi, thanks for really quick fix :).
I am testing with wurstmeister/kafka dockerhub image. Issue is fixed for version 0.10.2.1 of kafka.
Version 0.11.0.1 and 1.0 are still affected.

Good thing decompression works as should with all versions.

**Comment by zmstone** [comment]
@bosak fixed in klarna/kafka_protocol#39. could you give it a try ?

**Comment by zmstone** [comment]
to summarize:
for magic version 1, kafka added some constraints on the compressed wrapper message.
1. the wrapper message timestamp should exist when compressed messages have timestamp this is added since magic version 1 (0.10.x).
2. the wrapper message offset should not be -1 (0, or offset of the last message in compressed batch), this is added since 0.11

will send another PR here to have brod fixed later.

**Comment by bosak** [comment]
thanks!
gzip works with all versions now, after PR you can close this issue i guess
