### ISSUE TITLE
Question: Producing message with timestamp

### ISSUE THREAD

**Issue by objectuser** [kafka4beam/brod#253]
I'm able to successfully produce a message with a timestamp using `brod:produce_sync/5` and messages of the form `{Ts, Key, Message}`.

I'm wondering if this is the only way to produce a timestamp. For example, is there a way to produce messages where Brod supplies the timestamps?

Thanks!

**Comment by zmstone** [comment]
no, brod does not create timestamp.
only way for now is to call existing APIs with args `Key = <<>>` and `Value = [{Ts, Key, Msg}]`.

**Comment by zmstone** [comment]
and by the way, compression is broken for producers at the monment when timestamp is given
on going invstigation. see #252

**Comment by objectuser** [comment]
@zmstone Thanks, noted.
