### ISSUE TITLE
Produce behavior with list and partition function

### ISSUE THREAD

**Issue by objectuser** [kafka4beam/brod#255]
I'm calling `produce_sync/4` with a function and a list (including a timestamp):

```elixir
:brod.produce_sync(client, topic, &select_partition/4, "ignored",
      [{System.system_time(:milliseconds), key, message}])
```

It looks like the result of the partition function is ignored, but the `ignored` string parameter is being used to calculate the actual partition.

I'm obviously using this incorrectly. Can you tell me what I'm doing wrong?

Thanks!

**Comment by objectuser** [comment]
Now I may understand: when an function is provided, the key parameter is used for the partition. So where I have `"ignored"`, I should have `key` again.

**Comment by zmstone** [comment]
Yeah.
It’s documented only in README. We should probably make it more clear.

%% The top-level key is used for partitioning
%% and nested keys are discarded.
%% Nested messages are serialized into a message set to the same partition.

**Comment by objectuser** [comment]
Thanks!
