### ISSUE TITLE
problem restarting a group subscriber

### ISSUE THREAD

**Issue by danj3** [kafka4beam/brod#258]
I have a group subscriber that wants to consume 10k messages, then stop, then some time later listen for another 10k messages.

It seems that calling `brod_group_subscriber:stop( Pid )` is leaving the consumer in some unusable and not restartable state. When the resubscribe happens, I get something like the following:

(I am using brod from Elixir, but I can't image that would have an effect)
```
iex(6)> {:ok,pp} = Support.Tstore.Transaction.Source.start( Support.Tstore.Transaction.FractionEmitter, "ttest" )
{:ok, #PID<0.8887.0>}
iex(7)> 
14:10:32.680 [info]  Group member (ttest,coor=#PID<0.8888.0>,cb=#PID<0.8887.0>,generation=0):
connected to group coordinator kafka-server-2:9092
 
14:10:33.331 [info]  Group member (ttest,coor=#PID<0.3045.0>,cb=#PID<0.3043.0>,generation=45):
re-joining group, reason::RebalanceInProgress
 
14:10:42.681 [info]  Group member (ttest,coor=#PID<0.8888.0>,cb=#PID<0.8887.0>,generation=0):
failed to join group
reason::timeout
 
14:10:42.681 [info]  Group member (ttest,coor=#PID<0.8888.0>,cb=#PID<0.8887.0>,generation=0):
re-joining group, reason::timeout
 
14:10:52.681 [info]  Group member (ttest,coor=#PID<0.8888.0>,cb=#PID<0.8887.0>,generation=47):
elected=true
 
14:10:52.683 [info]  Group member (ttest,coor=#PID<0.8888.0>,cb=#PID<0.8887.0>,generation=47):
assignments received:
  transaction:
    partition=0 begin_offset=54806
    partition=1 begin_offset=52013
    partition=2 begin_offset=55609
    partition=3 begin_offset=53955
    partition=4 begin_offset=48756
    partition=5 begin_offset=52280
    partition=6 begin_offset=50178
    partition=7 begin_offset=42360
    partition=8 begin_offset=44805
    partition=9 begin_offset=44236
 
```

But no messages ever come in. I can restart the `brod` application/client, then process proceeds as it should. This tells me something isn't getting cleaned up properly.  I've been looking through `brod` and the tests for groups which seem to just use `stop`.

In case this matters, the handle_message function is the place where `stop` is being called, since it's using the `state` to keep track of the number of messages consumed.

Hints on what it could be or where I should look?

Many thanks.

**Comment by zmstone** [comment]
Hi @danj3 
I will try to reproduce it.

But are you sure the `stop` call was made in `handle_messages` callback?
Because that should cause a deadlock.

**Comment by danj3** [comment]
Ah! That's exactly what it was @zmstone. Since stop() does the monitor/receive, it was in fact deadlocked. In my handle_message I now put gen_server:cast( Pid, stop ) and now it's good. Is what I've done the right solution? I'm curious, why stop is written to block?

**Comment by zmstone** [comment]
It is a blocked call because it is a blocked call by its look.
It's to avoid race when a restart is triggered right after stop.
I guess what we need here is to introduce a new return code `{ok, stop, NewState}`.
