### ISSUE TITLE
v3.3.5 - Consumer group halts progression when restreaming a topic with cleanup.policy=compact

### ISSUE THREAD

**Issue by CJPoll** [kafka4beam/brod#263]
We are using a topic with cleanup.policy=compact. This allows us to maintain the entire dataset in a topic over time, with kafka cleaning up old versions of a particular key.

We scaled down the number of workers processing this topic to 0 over the weekend. When we brought them back up, kafka had already performed a compaction. The consumers in the consumer group made progress for a while, but halted progression when attempting to fetch a batch where the first offset in the batch had been cleaned up during the compaction.

Presumably, one could reproduce with the following steps:

1. Create a topic "abc" with `cleanup.policy=compact` (with a single partition for simplicity)
1. Publish a bunch of messages with unique key values
1. Publish a single message which has a key previously published in step 2 (We'll call the offset of this message `CompactedOffset`
1. Publish more data with unique key values
1. Force a compaction in kafka (¯\\_(ツ)_/¯)
1. `brod:fetch(KafkaHost, <<"abc">>, 0, CompactedOffset-1)` successfully returns a batch
1. `brod:fetch(KafkaHost, <<"abc">>, 0, CompactedOffset+1)` successfully returns a batch
1. `brod:fetch(KafkaHost, <<"abc">>, 0, CompactedOffset)` returns an empty list

We are using the `brod_group_subscriber` abstraction with version `3.3.5`, and in the cases where the first offset of a batch meet this condition, progress is halted.

As a workaround, we're able to resume progress by setting offsets to the next offset after that point which is not compacted, but given that we're processing some millions of events, this restream is becoming particularly painful with the amount of manual work required.

Is there something I'm missing/doing incorrectly?

**Comment by zmstone** [comment]
There is a consumer config `offset_reset_policy` which is by default `reset_by_subscriber`.
i.e. when consumer receives a "offset out of range" error from kafka, it waits for the subscriber to re-subscribe with a new `begin_offset` option.
Other possible configs are `reset_to_earliest` or `reset_to_latest`
I guess you need `reset_to_earliest` for your use case.

Will consider change default to `reset_to_earliest`.

**Comment by CJPoll** [comment]
Hmmm... unless I'm misunderstanding what those options do, I don't think any of those would work automatically. They would work fine if we were using a cleanup policy based on retention time, since there would be a contiguous set of messages. When using compaction instead of retention time, the log sometimes becomes non-contiguous.

|0|1|2|3|4|5
|a|b|c|X|e|f

^ For simplicity, let's say a consumer is consuming this log one message at a time. Offsets 0-2 exist and 4-5 exist, but 3 has been cleaned up. If using `reset_to_earliest`, the consumer would start over at 0 again, which would eventually put it in the same problem when it reaches offset 3. If choosing `reset_to_latest`, then it would jump to 5, thus skipping 4. 

Of note, the fetch is not returning `{error, "The requested offset is not within the range of offsets maintained by this server"}`. It is returning `{ok, []}`

**Comment by zmstone** [comment]
Hi. Sorry for not reading through your bug report.
I saw 'cleaned up' and 'halted', immediately assumed it was 'offset out of range'

This is new to me, If I remember correctly there was no such issue in kafka 0.9
which kafka version are you running? I'll try to reproduce it first.

**Comment by eloraburns** [comment]
I think we've hit this now as well, and we can't (as easily) just set offsets; the compacted topic is read fully on each app startup as its initial data set (with continued streaming updates).

In  our case, I've narrowed it down a bit: Kafka is definitely returning a `fetch_response` with 0 entries. In this particular case, it does this when the original messages that were compacted away are at the end of a segment, i.e.:
```
$ ls -l /var/opt/kafka/topic-42
total 34944
-rw-rw-r-- 1 kafka kafka      232 Jun 29 14:51 00000000000000000000.index
-rw-rw-r-- 1 kafka kafka  7415983 Jun 29 14:51 00000000000000000000.log
-rw-rw-r-- 1 kafka kafka      348 Jun 29 14:51 00000000000000000000.timeindex
-rw-rw-r-- 1 kafka kafka      320 Jun 29 15:58 00000000000000008748.index
-rw-rw-r-- 1 kafka kafka  9976668 Jun 29 15:58 00000000000000008748.log
-rw-rw-r-- 1 kafka kafka      480 Jun 29 15:58 00000000000000008748.timeindex

$ /opt/kafka/kafka_2.11-0.11.0.2/bin/kafka-run-class.sh kafka.tools.DumpLogSegments --files 00000000000000000000.log | tail -n1
baseOffset: 8737 lastOffset: 8747 baseSequence: -1 lastSequence: -1 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false position: 7406358 CreateTime: 1530283898463 isvalid: true size: 9625 magic: 2 compresscodec: NONE crc: 3655123754

# A closer look
$ /opt/kafka/kafka_2.11-0.11.0.2/bin/kafka-run-class.sh kafka.tools.DumpLogSegments --files 00000000000000000000.log --deep-iteration 2>&1 | grep -C 3 "Non-consecutive offsets"
offset: 8742 position: 7406358 CreateTime: 1530283898421 isvalid: true keysize: 7 valuesize: 771 magic: 2 compresscodec: NONE producerId: -1 producerEpoch: -1 sequence: -1 isTransactional: false headerKeys: []
offset: 8743 position: 7406358 CreateTime: 1530283898422 isvalid: true keysize: 7 valuesize: 779 magic: 2 compresscodec: NONE producerId: -1 producerEpoch: -1 sequence: -1 isTransactional: false headerKeys: []
offset: 8744 position: 7406358 CreateTime: 1530283898463 isvalid: true keysize: 7 valuesize: 1351 magic: 2 compresscodec: NONE producerId: -1 producerEpoch: -1 sequence: -1 isTransactional: false headerKeys: []
Non-consecutive offsets in :/var/opt/kafka/topic-42/00000000000000000000.log
  8694 is followed by 8696
  8652 is followed by 8654
  8614 is followed by 8616
```

Sure enough, a `:brod.fetch(…, 8743)` returns 2 entries, 8744 returns 1 entry, and any of fetching offsets 8745-8747 return an empty list. Offset 8748 returns a huge list of entries from the next segment. 😄 

Looking at the brod code, it does not appear to be written to take empty MessageSets into account. In `brod_consumer.erl`, `handle_message_set` punts on empty lists, and just schedules a future fetch without incrementing the offset.

It looks fixable because the protocol reply does include the partition's high water mark, so incrementing the offset and fetching again ought to be a safe and sensible thing to do. I'll dig in and see what I can do, as this is currently a blocker for us!

**Comment by zmstone** [comment]
@taavi Thanks! I'll work on a fix NOW.

**Comment by zmstone** [comment]
@taavi If you still have the kafka cluster running, could you help to verify if #275 works?

**Comment by eloraburns** [comment]
Cool! I do, and I will update us to 3.5.1 (to verify that it still halts) and then to the branch to verify that it's working. Thanks for the quick update! (I poked around in the code, and had just come up with exactly the same solution!)

**Comment by zmstone** [comment]
thanks for the tests.
I think I should be able to merge it tomorrow and publish to hex too (3.5.2).

**Comment by eloraburns** [comment]
Confirmed! Upgraded to 3.5.1  and that did not fix things. Upgraded to 3.5.2-pre (from the PR) and the topic progresses! Thanks so much for this!
