### ISSUE TITLE
Help understanding offset policies?

### ISSUE THREAD

**Issue by objectuser** [kafka4beam/brod#264]
I'm trying to understand the difference between the `begin_offset` setting and `offset_reset_policy`.

I thought that when a consumer began reading from a topic with a new group, only the `begin_offset` policy would have an effect. And that the `offset_reset_policy` would only take effect if a group had invalid offsets, like they had expired.

However, we just deployed a new consumer to a topic and it seemed to begin reading from latest. It was using `earliest` for `begin_offset` and `offset_reset_policy` of `reset_to_latest`. So my guess is that, since the consumer group was new, the `offset_reset_policy` took effect and it began reading from the latest.

If that's true, I'm not sure when `begin_offset` would be used. Looking at the code, it seems like it's a protocol-level thing.

Could you clarify when each is used?

Thanks!

**Comment by zmstone** [comment]
`begin_offset` is for a subscriber to tell `brod_consumer` where to start fetching messages.
`offset_reset_policy` is for `brod_consumer` to decide which offset to reset to
when a `OffsetOutOfRange` error code is received in `fetch_response`.

One possible cause is: you may have used an old consumer group ID,
and the old committed offset is out of range for current topic-partition,
then got reset to 'latest'. 
if this is the case, you should be able to find logs  'assignments received' log lines
with which offset for each partition found in the following lines.

**Comment by zmstone** [comment]
Also, if 'OffsetOutOfRange' error code is received, there should be a log line like this:
`offset out of range, applying reset policy reset_to_latest`

**Comment by zmstone** [comment]
Yes. with a bit more clarification:

> Existing consumer group with offsets expired => begin_offset doesn't matter, offset_reset_policy determines the behavior.

I assume by 'expired' you mean old kafka log segments being deleted by retention-policy,
hence the committed offset is 'OutOfRange' as 'too old'.
Needed to clarify because offset commit history may expire too -- in such case, it's `begin_offset` to be used.

**Comment by objectuser** [comment]
Thanks, that helps a lot, including your clarification. 

Much appreciated!
