### ISSUE TITLE
Add support for record headers

### ISSUE THREAD

**Issue by featalion** [kafka4beam/brod#266]
Since Kafka version 0.11.0 [record level headers](https://kafka.apache.org/documentation/#record) were introduce. Currently, nor `brod` library, nor underneath `kafka_protocol` do not support them.

Proposed record headers format is:

```erlang
-type in_record_header_key()   :: atom() | binary() | string().
-type in_record_header_value() :: binary() | string().
-type in_headers()             :: [{in_record_header_key(), in_record_header_value()}].

-type out_record_header_key()   :: binary().
-type out_record_header_value() :: binary().
-type out_headers()             :: [{out_record_header_key(), out_record_header_value()}].
```

The next APIs will be affected:
* `brod_producer`
* `brod_consumer`

**Comment by zmstone** [comment]
please wait for https://github.com/klarna/kafka_protocol/tree/support-kafka-1.0.0
will be supported as: https://github.com/klarna/kafka_protocol/blob/support-kafka-1.0.0/src/kpro.erl#L81

**Comment by featalion** [comment]
Thanks!
