### ISSUE TITLE
What's the best way to unsubscribe from topics?

### ISSUE THREAD

**Issue by objectuser** [kafka4beam/brod#268]
In [Kaffe](https://github.com/spreedly/kaffe/pull/59/files), I've implemented `brod_group_member`.

I now want to be able to unsubscribe from topics dynamically (while apps are running).

I notice that `brod_group_subscriber` ([here](https://github.com/klarna/brod/blob/master/src/brod_group_subscriber.erl#L371)) does `brod:unsubscribe/2`.

Is that what I should be doing?

Thanks!

**Comment by zmstone** [comment]
Hi @objectuser 

There is no need to explicitly call the unsubscribe API if the member is to be terminated.
Otherwise yes, call `brod:unsbcribe/2`

**Comment by objectuser** [comment]
Thank you!
