### ISSUE TITLE
SASLHandshake API-version compatibility check does not work correctly. 

### ISSUE THREAD

**Issue by RGafiyatullin** [kafka4beam/brod#269]
Brod does not validate SASLHandshake API-version at all (`brod_kafka_apis:supported_versions/1`).

This leads to a situation when upon trying to negotiate SASL-authentication with a server that only supports SASLHandshake-v1 the protocol-framing gets broken.

An ideal resolution of that situation in my opinion would be to support `SASLHandshake:1 + SASLAuthenticate:0` along with `SASLHandshake:0 + InBand-SASLNegotiation`.

**Comment by zmstone** [comment]
Hi @RGafiyatullin 
This is a work in progress. Sending PR to support handshake soon.

**Comment by zmstone** [comment]
fixed in latest master. closing it now.
