### ISSUE TITLE
Adding timestamp metadata to kafka messages

### ISSUE THREAD

**Issue by shashank88** [kafka4beam/brod#270]
As of Kafka v0.10 each message contains a meta data timestamp attribute, that is either set by the producer on message creation time, or by the broker on message insertion time. Are there plans to add this to brod so this can be set at the produce time or is there something similar we can use? 

https://cwiki.apache.org/confluence/display/KAFKA/KIP-32+-+Add+timestamps+to+Kafka+message#KIP-32-AddtimestampstoKafkamessage-AddatimestampvariabletoRecordMetadata

https://stackoverflow.com/questions/39514167/retrieve-timestamp-based-data-from-kafka

**Comment by zmstone** [comment]
Hi @shashank88 I believe it's already supported in `brod`
see `#kafka_message.ts_type` and `#kafka_message.ts` which are defined here: https://github.com/klarna/kafka_protocol/blob/1.1.2/include/kpro_public.hrl#L27-L28

An example to produce message with timestamp:
`brod:produce(Client, Topic, Partition, _PartitionKey = <<>>, _Messages = [{Timestamp, MessageKey, MessageValue}])`

**Comment by shashank88** [comment]
@zmstone Thank you!
