### ISSUE TITLE
Support for Kafka 1.1.1?

### ISSUE THREAD

**Issue by madshargreave** [kafka4beam/brod#280]
Does Brod currently support Kafka 1.1.1+?

**Comment by zmstone** [comment]
Hi @madshargreave 
It depends on what you need.
It supports the latest produce/fetch API versions.
But not all APIs are supported, and we do not plan to support all.
see https://github.com/klarna/brod/blob/master/src/brod_kafka_apis.erl#L137-L153

**Comment by madshargreave** [comment]
Thanks for the quick response

Alright. Is it correct that the documented Brod usage examples should still work with the new version, without further changes?

**Comment by zmstone** [comment]
Yes.
All old APIs exposed from `brod.erl` are backward compatible.

**Comment by madshargreave** [comment]
Beautiful, thank you
