### ISSUE TITLE
Problems when losing kafka connection

### ISSUE THREAD

**Issue by XOfSpades** [kafka4beam/brod#281]
I created a minimal example for a kafka consumer. Maybe I am doing something wrong, but in case the application loses the connection to kafka the consumer does not come up again properly.

Here is my minimal example:
https://github.com/XOfSpades/minimal_brod_example

Steps to reproduce:
- start kafka (maybe adopt the port)
- produce a message which will create a console output of the message
- restart kafka (e.g. with a `docker-compose down && docker-compose up -d`)
- produce again a message

The last message won't be shown. 

I already recognized that the main process of brod seems to come back again:

```
iex(1)> GenServer.whereis(:brod_kafka_base_server)
#PID<0.244.0>
```

If this is anyhow important I am using:
- Elixir 1.7.2
- docker image confluentinc/cp-kafka:4.1.0
- docker image confluentinc/cp-zookeeper:4.1.0

Takk for hjelped :-)

**Comment by XOfSpades** [comment]
btw I used a one node kafka here

**Comment by zmstone** [comment]
Hi @XOfSpades 
could you provide some logs especially the restart logs after kafka restart.
e.g. consumer group partition assignment logs

**Comment by zmstone** [comment]
your application is down and I can't seem to find the start log:

> 14:18:41.973 [info] Application minimal_brod_example exited: shutdown

you'll need to restart the group subscriber after bord client is back.
in practice, you may want to manage your brod_group_subscriber worker under `supervisor3`
which can be configured to retry restart indefinitely.

**Comment by XOfSpades** [comment]
Thank you. Found it
