### ISSUE TITLE
maybe_init_connection must reset connection?

### ISSUE THREAD

**Issue by jbucar** [kafka4beam/brod#285]
Hi, We have a problem with brod_consumer:subscribe that returns 
 NotLeaderForPartition or
 LeaderNotAvailable
in some situations (kafka in kubernetes killing pods with chaoskube for example).

The problem is that consumer have the leader cached in the state (field connection) and we need to kill the consumer to fix the problem. Is it the correct fix?

We believe that a better solution to the problem is reset the leader connection and call to
   brod_consumer:maybe_init_connection

Where to fix:
Always in brod_consumer:subscribe reset connection, it query again kafka cluster to get the leader.

Another posible solution is catch the error in brod_consumer:handle_fetch_error
For example:
In err_op add 
    err_op(?NotLeaderForPartition) -> reset_connection;
    err_op(?LeaderNotAvailable) -> reset_connection;
and in brod_consumer:handle_fetch_error reset the connection
  case err_op(ErrorCode) of
       reset_connection -> 
            State1 = State0#state{ connection = ?undef },
            maybe_send_init_connection(State1)
With a backoff to call 
    restart ->
      ok = cast_to_subscriber(Subscriber, Error),
      {stop, {restart, ErrorCode}, State}

Thanks in advance
Javier

**Comment by zmstone** [comment]
Hi @jbucar 
Which `brod` version do you use ?
I'm not quite sure why you have to kill the consumer to fix the problem.
In latest master implementation, `not_leader_for_partition` and `leader_not_available` error codes will cause `brod_consumer` to restart then it should discover a new connection after restart.

**Comment by jbucar** [comment]
Hi @zmstone , thanks!
We are using tag 3.5.0. The code to restart the subscriber is there, but we call to subscribe without wait .... to fix it we need to wait and poll the consumer pid until consumer start again .... not very elegant but fix the problem.

**Comment by zmstone** [comment]
I see.
I agree adding special handling for `not_leader_for_partition` and `leader_not_available` would make it more resilient to leader migration/restart. I'll see if I can prepare a PR over the weekend.
However, 'wait and poll' is needed regardless, because there is always a chance for `brod_consumer` to crash.
