### ISSUE TITLE
Add an option to subscribe on a topic

### ISSUE THREAD

**Issue by id** [kafka4beam/brod#29]
Right now we only have brod:subscribe/5 which allows users to subscribe on specific partition. And user application must also monitor brod_consumer process.
- User's process should be able to subscribe on a topic in one call
- User's process should not be required to monitor brod internal processes in order to work reliable

**Comment by zmstone** [comment]
the start_link_xxx_streamer idea we talked about?
xxx could be partition, topic or group.

**Comment by id** [comment]
Kind of, yes.

I think we can still use the same brod:subscribe API (to not confuse users too much), but internally it could be a special process managing partition consumers.

**Comment by zmstone** [comment]
yes, a streamer should be subscriber of one or more partitions.
