### ISSUE TITLE
Retrieving current assignments from group subscriber and topic-partition leader connection health check

### ISSUE THREAD

**Issue by arkgil** [kafka4beam/brod#295]
Hello,

First of all, thank you for the amazing job you're doing with this library - it has worked really well for us! ❤️ 

Now, to the real issue. I'm in the process of implementing the health check for one of our services using Kafka with `brod_group_subscriber`. One possible way to do this would be to get the current assignments of group subscriber and for each topic-partition assigned check whether the partition worker has opened connection to the leader.

Would you be interested in PR for such functionality? Or should I rather fork? Or maybe there is some already available solution to the problem?

**Comment by zmstone** [comment]
Hi @arkgil 
Why don't you base you health-check on offset lagging checks ?
There are tools for this,
such as burrow https://github.com/linkedin/Burrow
and kastlex (which we use at klarna) https://github.com/klarna/kastlex

Nonetheless, I'm interested to see your idea in code, so feel free to send a PR.

**Comment by arkgil** [comment]
Thanks for the suggestion @zmstone! I really like the idea behind those tools, and would prefer to use them. I'll see if they can be applied with our current constraints and I'll get back here.

**Comment by arkgil** [comment]
@zmstone we'll go with Burrow, thanks again for the suggestion! I'm closing the issue 🙂
