### ISSUE TITLE
nxdomain

### ISSUE THREAD

**Issue by ForLina** [kafka4beam/brod#302]
Hello, I got a problem.
`call gen_tcp:connect("120.55.*.*",9092,[{active,false},binary],5000)
(<0.293.0>) returned from gen_tcp:connect/4 -> {ok,#Port<0.36>}
(<0.305.0>) call gen_tcp:connect("iZbp183fyu7ocokoaq78h7Z",9092,[{active,false},binary],5000)
(<0.305.0>) returned from gen_tcp:connect/4 -> {error,nxdomain}
23:58:07.332 [error] client client1 failed to connect to iZbp183fyu7ocokoaq78h7Z:9092`

 I wrote some code just follow your example, and I got this problem when I connect to kafka server.  'iZbp183fyu7ocokoaq78h7Z' is the host name of 120.55.*.*. I wonder why will connect to kafka server by host name. And how to fix it?

**Comment by aegirsystems** [comment]
having a similar problem, did you find a resolution.

**Comment by zmstone** [comment]
@aegirsystems Looks like the brokers are advertising themselves with non resolvable hostnames to clients.
check `advertised.listeners` in kafka server.properties

**Comment by aegirsystems** [comment]
Checking that now - here is the error:

ok = brod:produce_sync(client1, Topic, 0, "00101", "This is the value"),

2020-03-24T15:49:07.989392-04:00 error: client client1 failed to connect to S1-Kafka-1:9092, reason:{nxdomain,[{kpro_connection,connect,4,[{file,"/home/roger/IdeaProjects/redis/_build/default/lib/kafka_protocol/src/kpro_connection.erl"},{line,207}]},{kpro_connection,init,4,[{file,"/home/roger/IdeaProjects/redis/_build/default/lib/kafka_protocol/src/kpro_connection.erl"},{line,170}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}

**Comment by aegirsystems** [comment]
so it is interesting - i am running a java producer and it is working perfectly - but i want to move everything out of Java and to Erlang for performance and scaleability reasons.

**Comment by aegirsystems** [comment]
you are spectacular - that was the problem--- working as expected. thank you...

advertised.listeners=PLAINTEXT://10.10.1.35:9092
