### ISSUE TITLE
Unclear doc about topic subscriber

### ISSUE THREAD

**Issue by ukrbublik** [kafka4beam/brod#307]
brod_topic_subscriber - what group id does it have? Some default value or randomly generated?
How 2 apps with topic subscribers to same topic will work together? Will they consume messages in parallel?

**Comment by k32** [comment]
Hi,

`brod_topic_subscriber` is a primitive behavior which doesn't have a group id. Topic subscriber processes work completely independently, i.e. they simply consume all messages in the specified topic/partition starting from the specified offset.
