### ISSUE TITLE
Receive notification about rebalance

### ISSUE THREAD

**Issue by dntsv** [kafka4beam/brod#315]
Hi!

I was searching for a way to receive notification about the rebalance events. I mean when the rebalance triggers and the group coordinator will call back all of the assignments to reassign them. 

You implemented the brod_group_member behaviour which is i suppose the thing i am looking for. But unfortunately brod_group_subscriber is implementing it and it can not be changed now. How about using a MemberModule which will implement the behaviour instead of ?MODULE in brod_group_subscriber:init/1 ? This way i can use the subscriber but also add some extra code to the callbacks.

Am i missing something ? As far as i know this is implemented in the java client but is there any way to receive these events in brod ?

Thanks

Edit: I am using this now:
[https://github.com/dntsv/brod/commit/b79502d2dbc881aa96a35df5be36d5fb7c65fb6c](url)

**Comment by zmstone** [comment]
Hi!
Sorry for the late replay. You commit is deleted?

Currently, the only way for `brod_group_subscriber` callback to know a rebalance happened
is to implement the `assign_partitions` callback and us `callback_implemented` in config.
However, this callback is only evaluated by the leader member.

If you mean to pass down `brod_group_member` behaviour callbacks to `brod_group_subscriber` callback module ?
That's a non backward compatible change.
Perhaps better to add a `assignments_revoked` optional callback to `brod_group_subscriber` behaviour.
`assignments_revoked` is always called at the beginning of each group rebalance.

**Comment by dntsv** [comment]
Hello!

I haven't deleted it just messed the link above (here it is again):
[https://github.com/dntsv/brod/commit/b79502d](https://github.com/dntsv/brod/commit/b79502d2dbc881aa96a35df5be36d5fb7c65fb6c)

So basically i just separated `brod_group_member `behaviour callbacks from the `brod_group_subscriber `module. I implemented those in my custom member module. In my version ` assignments_received` and `assignments_revoked` are both sending a message to my target process (the one which requires the notification). After that they execute the same call/cast, which is the customisation i needed.
