### ISSUE TITLE
Brod consumer crashing

### ISSUE THREAD

**Issue by andyleclair** [kafka4beam/brod#321]
Hello!

I'm seeing a lot of this error when trying to consume messages from my Kafka topic:

```
[warn] :brod_consumer #PID<0.667.0> terminating, reason:
{{:badmatch, []}, [{:brod_consumer, :handle_fetch_response, 2, [file: 'src/brod_consumer.erl', line: 345]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 637]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 711]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}
[error] GenServer #PID<0.667.0> terminating
** (MatchError) no match of right hand side value: []
    (brod) src/brod_consumer.erl:345: :brod_consumer.handle_fetch_response/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:msg, #PID<0.568.0>, {:kpro_rsp, :fetch_response, 3, 10, [throttle_time_ms: 3850, responses: []]}}
State: {:state, #PID<0.522.0>, #PID<0.568.0>, "events", 1, 863982, 10000, 0, 1000000, 1000, 10, 10, #PID<0.672.0>, #Reference<0.2582508310.2267021315.10354>, {:pending_acks, 0, 0, {[], []}}, false, :reset_to_latest, 2221.6738961909596, 1000000, 5, 102400}
```

For reference, I'm using `brod` 3.4 (in Kaffe). I'm using Erlang 21.1 and elixir 1.8.1.

**Comment by andyleclair** [comment]
From looking at the code, it appears that brod is trying to pattern match a nonempty list. Does this mean I'm getting `[]` back from kafka and brod is handling it improperly? Or have I configured something wrong? FWIW I'm using hosted kafka from Confluent and connecting with SASL over SSL

**Comment by zmstone** [comment]
I guess it's consuming a partition which has producers doing transactional stuff.
Please upgrade to latest version.

**Comment by andyleclair** [comment]
What do you mean by transactional stuff? Our producers are calling `produce_sync` only. Are you saying that the consumer is trying to read a record that's not been fully committed yet?

Would upgrading solve this problem? Sorry if this question is basic, I'm a little new to Kafka in general

**Comment by zmstone** [comment]
The only case that I know of in which kafka may send an empty `responses` filed
is when it gets a a session init message,
however, I can no longer reproduce it,
Could you provide more info about kafka and your topic config?
e.g. which kafka version is it? is it a compacted topic?
would be even better if you may provide a way to reproduce this.

**Comment by zmstone** [comment]
Sorry that I replied too fast based on my vague memory,
transactional producer and incremental fetch got mixed up in my head.

Now I managed to reproduce the empty `response` field,
but it's only for fetch request version 7 or above, which is not supported in brod 3.4.

If you are interested in what may happen for version 7 or later:
https://github.com/klarna/kafka_protocol/pull/53/files
In the above test, the consumer tries to initialise a fetch session,
then it tries to fetch the latest offset and expects an empty `response` field,
which implies, since the last fetch in this session, there were:
1) no new message
2) no high-watermark offset change (or any other metadata change) either.

**Comment by andyleclair** [comment]
@zmstone I've confirmed that updating our brod version fixes the issue. Thank you for taking the time to look into this!

**Comment by zmstone** [comment]
Hi again @andyleclair 
Which kafka version was it that you had issue with?

**Comment by andyleclair** [comment]
@zmstone I'm not sure what kafka version it was. We're using Confluent hosted Kafka, so I'm not exactly sure?

**Comment by zmstone** [comment]
I found that kafka 2.0 may send empty responses when consumer is throttled (rate limited).
Wanted to double check if you were connecting to something else.
Thanks anyway @andyleclair
