### ISSUE TITLE
Incompatible Host and Port Config Changes in >= 3.5?

### ISSUE THREAD

**Issue by objectuser** [kafka4beam/brod#324]
Looking through the code, I'm not sure I see where this change might have happened, but we think version 3.5 introduced an incompatibility. We used to be able to use atoms for host names. Now it seems we have to specify binaries. We've been discussing it a bit in a Kaffe issue [here](https://github.com/spreedly/kaffe/issues/75).

Is this a known change?

**Comment by zmstone** [comment]
Hi.
`brod` only supports Erlang `string()` (single quoted string in Elixir) as hostname, not `atom()` not `binary()` (double quoted string in Elixir) either.

**Comment by zmstone** [comment]
There were no changes with regards to brod:endpoint() spec from 3.4 to 3.5 either.

**Comment by objectuser** [comment]
I'm not sure I'm tracing it correctly, but in 3.4 if I pass an atom, I end up [here](https://github.com/klarna/brod/blob/1fe715ea23d354793cc1e51ec622a3ee8f29c9db/src/brod_client.erl#L712) and then [here](https://github.com/klarna/brod/blob/1fe715ea23d354793cc1e51ec622a3ee8f29c9db/src/brod_sock.erl#L170) with still having an atom and all goes well.

With the newer versions, I end up inside `kpro_connection` from `kafka_protocol` and get an error:

```
2019-05-30 08:45:44.984 [error] GenServer :s1 terminating
** (FunctionClauseError) no function clause matching in :kpro_connection.host/1
    (kafka_protocol) src/kpro_connection.erl:579: :kpro_connection.host(:kafka)
    (kafka_protocol) src/kpro_connection.erl:101: :kpro_connection.start/3
    (kafka_protocol) src/kpro_brokers.erl:304: :kpro_brokers.connect_any/3
    (brod) src/brod_client.erl:524: :brod_client.ensure_metadata_connection/1
    (brod) src/brod_client.erl:279: :brod_client.handle_info/2
```

I'm going to try converting everything to Erlang strings and see if that works across versions.

**Comment by objectuser** [comment]
Looks like if we always transform to Erlang strings (Elixir charlists) it works for both newer and older versions of Brod.

**Comment by zmstone** [comment]
will be fixed here: https://github.com/klarna/kafka_protocol/pull/56
