### ISSUE TITLE
How to create Kafka topic manually or automatically

### ISSUE THREAD

**Issue by ZombieSir** [kafka4beam/brod#335]
I use Brod as a plug-in to connect EMQ and kafka. I need to ensure that the topic of EMQ is consistent with that of kafka. So how to create the topic of Kafka manually or automatically through brod?

**Comment by k32** [comment]
You can use https://github.com/klarna/kafka_protocol library (brod uses it under the hood):
```
  TopicFields = [ {topic, Name}
                , {num_partitions, NumPartitions}
                , {replication_factor, 1}
                , {replica_assignment, []}
                , {config_entries, [ [{config_name,"max.message.bytes"}
                                     ,{config_value, "20485760"}] ]}], % ~20 MB
  Req = kpro_req_lib:create_topics( 0
                                  , [TopicFields]
                                  , #{timeout => 5000}
                                  ),
  {ok, Conn} = kpro:connect_any([{?KAFKA_HOST, ?KAFKA_PORT}], []),
  {ok, _Res} = kpro:request_sync(Conn, Req, 5000),
  kpro:close_connection(Conn)
```

**Comment by ZombieSir** [comment]
I hope I can create my own topic like this:
        ClientConfig = [{allow_topic_auto_creation,true},{auto_start_producers,true},{default_producer_config,[]}],
	ok = brod:start_client(KafkaBootstrapEndpoints, brod_client_1, ClientConfig),
	ProducerConfig = [],
        ok = brod:start_producer(brod_client_1, Topic, ProducerConfig),
        ...
        {ok, CallRef} = brod:produce(brod_client_1, Topic, Partition, ClientId, list_to_binary(Json)),
        ...
this will create a topic in kafka, but it will report errors:
        error,unknown_topic_or_partition
and I want to ensure a certain degree of concurrency。
                                                                                                               Thank you very much. Good luck.

**Comment by ZombieSir** [comment]
I hope I can create my own topic like this:
         ClientConfig = [{allow_topic_auto_creation,true},{auto_start_producers,true},{default_producer_config,[]}],
	 ok = brod:start_client(KafkaBootstrapEndpoints, brod_client_1, ClientConfig),
	 ProducerConfig = [],
         ok = brod:start_producer(brod_client_1, Topic, ProducerConfig),
         ...
         {ok, CallRef} = brod:produce(brod_client_1, Topic, Partition, ClientId, list_to_binary(Json)),
         ...
this will create a topic in kafka, but it will report errors:
         error,unknown_topic_or_partition
and I want to ensure a certain degree of concurrency。
                                                                                                               Thank you very much. Good luck.

**Comment by Coffei** [comment]
Facing the same situation. It seems rather strange, that even with `allow_topic_auto_creation` set to `true` a produce to non-existent topic generates an error, creates the topic but doesn't put the message into the topic. Should I re-send the message on such error?

IMO it would make more sense if the topic existence would be concealed from the user in such situation. If the topic doesn't exist and produce is called, it would create the topic and put the message in that topic. By setting `allow_topic_auto_creation` you declare you don't care if the topic does or doesn't exist at the time of the produce.

**Comment by Coffei** [comment]
I was curious how the official Java client behaves, so I verified it and it does exactly what I described as the ideal behavior - creates the topic, publishes the message and returns OK response.

Should we consider changing this behavior in brod?

**Comment by SoniCoder** [comment]
@Coffei 
I agree with your point. My use case is also exactly the same. For the first time, while producing to a topic which doesn't exist, if kafka's auto.create.topics.enable is set to true, we shouldn't get a response like unknown_topic_or_partition

**Comment by v-kat** [comment]
@ZombieSir https://github.com/klarna/brod/pull/348 might help

**Comment by k32** [comment]
Closing this issue since @IRog implemented a new API in brod.
