### ISSUE TITLE
Publish doc to hex

### ISSUE THREAD

**Issue by chulkilee** [kafka4beam/brod#337]
It would be great if I can check out all docs online, not digging into source code :)

I don't know what's the conventional place for erlang library docs.. but as `brod` is available at hex, at least let's push the doc to hex using 
[rebar support](https://www.rebar3.org/docs/hex-package-management#section-docs).

See [telemetry](https://hex.pm/packages/telemetry) for an example.

**Comment by k32** [comment]
Good idea. Done: https://hexdocs.pm/brod/index.html
