### ISSUE TITLE
Support Microsoft azure event hub

### ISSUE THREAD

**Issue by XOfSpades** [kafka4beam/brod#345]
Hi we are currently migrating our applications from our own servers to Microsoft Azure and thus replacing kafka by event hub. Currently I try to connect to it, but constantly getting crashes when starting the brod client. Since they are considered to be compatible I might do something wrong. 
This is how I start it:

```
endpoints = [{
  "some_dummy_endpoint.windows.net",
  9094
}],
brod_client_config = [{:sasl, {
  :plain,
  "$User",
  "Endpoint=sb://some_dummy_endpoint.windows.net;with_a_lot_of_other_chars",
}}],

:brod.start_client(
        endpoints,
        :some_id,
        brod_client_config
      )
```
This results in the mentioned crash:

{“crash_reason”:"{[{{“some_dummy_endpoint.windows.net”, 9094}, {{{:kpro_req, #Reference<0.2235917605.3298295810.118099>, :api_versions, 0, false, “”}, :closed}, [{:kpro_lib, :send_and_recv_raw, 4, [file: ‘src/kpro_lib.erl’, line: 71]}, {:kpro_lib, :send_and_recv, 5, [file: ‘src/kpro_lib.erl’, line: 82]}, {:kpro_connection, :query_api_versions, 4, [file: ‘src/kpro_connection.erl’, line: 246]}, {:kpro_connection, :init_connection, 2, [file: ‘src/kpro_connection.erl’, line: 233]}, {:kpro_connection, :init, 4, [file: ‘src/kpro_connection.erl’, line: 170]}, {:proc_lib, :init_p_do_apply, 3, [file: ‘proc_lib.erl’, line: 249]}]}}], [{:brod_client, :ensure_metadata_connection, 1, [file: ‘src/brod_client.erl’, line: 548]}, {:brod_client, :handle_info, 2, [file: ‘src/brod_client.erl’, line: 298]}, {:gen_server, :try_dispatch, 4, [file: ‘gen_server.erl’, line: 637]}, {:gen_server, :handle_msg, 6, [file: ‘gen_server.erl’, line: 711]}, {:proc_lib, :init_p_do_apply, 3, [file: ‘proc_lib.erl’, line: 249]}]}",“erlang_pid”:"#PID<0.5099.0>",“file”:“gen_server.erl”,“function”:“error_info/7”,“hostname”:“aca2d00fc651”,“level”:50,“line”:889,“module”:“gen_server”,“msg”:“GenServer :my_app_kafka_client terminating\n** (stop) [{{“some_dummy_endpoint.windows.net”, 9093}, {{{:kpro_req, #Reference<0.2235917605.3298295810.118099>, :api_versions, 0, false, “”}, :closed}, [{:kpro_lib, :send_and_recv_raw, 4, [file: ‘src/kpro_lib.erl’, line: 71]}, {:kpro_lib, :send_and_recv, 5, [file: ‘src/kpro_lib.erl’, line: 82]}, {:kpro_connection, :query_api_versions, 4, [file: ‘src/kpro_connection.erl’, line: 246]}, {:kpro_connection, :init_connection, 2, [file: ‘src/kpro_connection.erl’, line: 233]}, {:kpro_connection, :init, 4, [file: ‘src/kpro_connection.erl’, line: 170]}, {:proc_lib, :init_p_do_apply, 3, [file: ‘proc_lib.erl’, line: 249]}]}}]\n (brod) src/brod_client.erl:548: :brod_client.ensure_metadata_connection/1\n (brod) src/brod_client.erl:298: :brod_client.handle_info/2\n (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4\n (stdlib) gen_server.erl:711: :gen_server.handle_msg/6\n (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3\nLast message: :init”,“name”:“My_App”,“pid”:1,“registered_name”:“my_app_kafka_client”,“time”:“2019-09-20T08:41:18.971Z”,“v”:0}

From the documentation of eventhub I found the following information: https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-for-kafka-ecosystem-overview

As far as I understood it brod tries to request the supported protocol version of the related kafka. This is just an educated guess, but could it be that here eventhub might not return a proper version? 

Anyway I will continue to investigate.

Thanks in advance / Mange takk for hjelped deres ;-)

**Comment by k32** [comment]
Hi!

Unfortunately we have no means of testing Azure Event Hub at this moment, nor can we guarantee that brod can work with this service.
A cursory look at the error looks like the remote port was closed or, possibly, could not be opened. I would start with checking network configuration: ports, firewalls, ssl configuration, etc.

**Comment by XOfSpades** [comment]
ok, thank you so far

**Comment by zmstone** [comment]
is port 9094 SASL_PLAIN or SASL_SSL?
looks like the connection process tried to query kafka api versions while kafka is expecting ssl handshakes.

**Comment by k32** [comment]
Hi @XOfSpades ! Did you have any luck with azure event hub? It is interesting how good their emulation layer is.

**Comment by XOfSpades** [comment]
Hi, I was on vacation the last week and before there was a lot of other stuff to do... I hope I can continue on the topic soon. I will let you know if I come further.

**Comment by hoarf** [comment]
I have managed to connect and get messages from azure but brod is failing in the drop_aborted function when it tries to fold the aborted_transactions because the value is null instead of empty lisy

**Comment by mmacai** [comment]
@hoarf can you please share how you connected to Azure Event hub? Can't get through handshake errors.
