### ISSUE TITLE
Implement offsetsForTimes 

### ISSUE THREAD

**Issue by leehambley** [kafka4beam/brod#360]
In the Java libraries for Kafka there's a function `offsetsForTimes`, https://kafka.apache.org/0102/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#offsetsForTimes(java.util.Map)

Given a a list of topics and a date in the past this returns:

> the earliest offset whose timestamp is greater than or equal to the given timestamp in the corresponding partition.

The use for this API is for stateless consumers who need to read historical data, and then keep consuming, they don't have their own storage, so a restart resuming from their last committed offset leaves them not knowing about activity before they started.

This API is exposed in Java, librdkafka and a handful of clients in other languages. It is far from ubiquitous.

**Comment by k32** [comment]
Hi @leehambley ! Did you try `brod:resolve_offset/5` offset function?

**Comment by leehambley** [comment]
Hi @k32 I missed that in the docs - I was searching for things with similar API naming to rdkafka. This looks more than suitable.

Closing, thanks sincerely! :tada:
