### ISSUE TITLE
Adding topic to group_coordinator

### ISSUE THREAD

**Issue by DianaOlympos** [kafka4beam/brod#372]
In my application, i have a use case in which we generate topics dynamically and then consume them through consumer group with sticky assignment.

It means that i need my group_coordinator to update its list of topic it asks for.

Right now, afaik, it means stopping the coordinator and starting a new one with the new list. Which would mean a rebalance when leaving and one when joining. And losing the stickyness.

I see two possible solutions to that problem:
1. add support for updating the list of topic. That would mean triggering a join_group when that is done.
2. Allow to set the new `group.instance.id` in the group_coordinator config and allow to trigger a join. 
This allow to do sticky/static membership. If one instance_id is setup, stopping the consumer would not trigger a leave. Like that we can rejoin, keep our sticky instance.id and our assignments then trigger a join by ourselves. (see [https://cwiki.apache.org/confluence/display/KAFKA/KIP-345%3A+Introduce+static+membership+protocol+to+reduce+consumer+rebalances](https://cwiki.apache.org/confluence/display/KAFKA/KIP-345%3A+Introduce+static+membership+protocol+to+reduce+consumer+rebalances))

I can work on doing a PR for any (or both of them), would there be an interest in any of them ?

**Comment by DianaOlympos** [comment]
Ok after thinking about it a bit more, what is needed is to be able to trigger a join in the group. That is not exposed right now, i will see if i can do a PR

**Comment by zmstone** [comment]
Hi @DianaOlympos sticky assignment is not supported today.
the underlying `kafka_protocol` library does not support `group.instance.id` yet.
work (spare time) in progress.
The workaround is to make use of user metadata (that's how it was recommended before `group.instance.id` was introduced to kafka protocol).

You can implement the `MemberModule:assign_partitions(MemberPid, Members, AllPartitions);` callback to perform a sticky assign.
However, stopping the coordinator will trigger a leave group request sent to kafka,
you can perhaps send a PR to prohibit that with a config, then set a relatively long session timeout.

(in fact, if the protocol is upgraded to support `group.instance.id`, kafka would not allow a leave group request)

**Comment by DianaOlympos** [comment]
Yes, hence the idea of allowing to trigger a "joingroup". In theory we should be able to trigger a join group with someone that is already a group member.

Handling sticky assignment is already something i am doing with user_data indeed.
The only problem here is that i need to be able to trigger a rebalance when i add topics dynamically.

In that case, rejoining with a new set of topics should be enough no ? And afaik you can rejoin if you already exist in without a leave. Am i missing something ?

**Comment by zmstone** [comment]
OK. I did not fully understand your idea.
I thought you meant to use `group.instance.id` in kafka protocol.
 
My idea was to add a config to avoid sending leave group in the terminate callback,
then restart with a new set of topics.
However I am not entirely sure if this approach will work as the broker coordinator may keep waiting for the old member to re-join and eventually timeout, or the coordinator is perhaps smart enough to know the absence of a member if the tcp connection is down.

Your approach seems more reasonable, i.e. start a rebalance with the current member-id.
Let's try it out if it works first, and discuss details in the PR.
looking forward to it.

**Comment by DianaOlympos** [comment]
closed by https://github.com/klarna/brod/pull/374
