### ISSUE TITLE
Support for altering topic configs

### ISSUE THREAD

**Issue by bjosv** [kafka4beam/brod#387]
Hi!
In one of our projects we need to have different topic configs depending on what the topics are used for, and today we solve this by using kafka-topics.sh to alter the config in a bit hackish way.
It would be much nicer to be able to use brod for this step aswell.

After having looked into this I've seen that supporting the Kafka messages `describe_configs` and `alter_configs` would give what we need, and I would like to discuss if the handling of topic configs is something we could bring in?

I have not looked at how the API in brod could look like, but I have done tests by adding support in the kafka_protocol and it does the job on that level.

I will push a PR to kafka_protocol for the protocol part and will happily get your thoughts/comments about an API like this, maybe there already are decisions or thoughts how to handle the AdminClient area?

**Comment by k32** [comment]
Hej @bjosv! 
Can we consider this issue solved?

**Comment by bjosv** [comment]
Hej!
Yes, sorry, had a plan to add an api to brod aswell, but this is good for now.
Closing this, thanks
