### ISSUE TITLE
Does brod support producing w/o specifying a partition?

### ISSUE THREAD

**Issue by amorphid** [kafka4beam/brod#391]
Does brod support producing w/o specifying a partition?  It looks brod:produce/5 requires a partition, and I'm not seeing an alternative approach.

**Comment by zmstone** [comment]
```
-spec produce(client(), topic(), partition() | partitioner(),
              key(), value()) -> {ok, call_ref()} | {error, any()}.
```
please have a look at the `partitioner()` spec.

**Comment by lud** [comment]
Hi, 

The partioner spec is the following: 

```
-type partitioner() :: partition_fun() | random | hash.
```

It seems like a fun must return a partition (integer), and that `random` and `hash` will also return an integer. Is it possible to let Kafka pick the partition, based on the key ?

Thank you.

**Edit**

Well it seems that such thing does not exists, and when talking about producer partition, what all websites/turorials call "Kafka" is actually the Java library ...

It seems that I have to implement `Utils.toPositive(Utils.murmur2(keyBytes)) % numPartitions` in erlang now.

**Comment by zmstone** [comment]
seems to be one here https://github.com/silviucpp/erl_hash/blob/1c6357eedfe999a3fdcb6e47406d5d18a8cd5853/src/erl_hash.erl#L11

**Comment by lud** [comment]
Yep! I found that one too. Thank you.
