### ISSUE TITLE
ts field is not produced

### ISSUE THREAD

**Issue by ahmetSimsek13** [kafka4beam/brod#394]
when sending produce to kafka as below

Key= <<"service.test1">>,
Value = "{\"version\": \"0.2\",\"faultName\": \"test1\"}"
Msg = [#{key => _Key, value => _Value, ts => kpro_lib:now_ts()}],
{ok, Ref} = brod:produce(brod_client1, Topic, 0, _Key, _Msg),

and checked logs of my alarm handler, timestamp field still remains -1 which causes failure in my case. How can i solve this ?

FaultIndication: ConsumerRecord(topic=u'testtopic', partition=0, offset=37, timestamp=-1, timestamp_type=0, key='service.test1', value='{"version": "0.2","faultName": "test1"}', checksum=-693020942, serialized_key_size=17, serialized_value_size=118)

**Comment by zmstone** [comment]
Two possible reasons:
1. Kafka version 0.10 starts supporting message timestamps, so if Kafka is 0.9, brod will drop ts (but I guess it's unlikely unless you have set `query_api_versions` flag to false.
2. The consumer does not support a newer `Fetch` API, so Kafka downgraded the message before sending it to the consumer.
