### ISSUE TITLE
Publish 3.11 on hex.pm?

### ISSUE THREAD

**Issue by joaquimadraz** [kafka4beam/brod#399]
Hi there,

I'm using brod on an Elixir application and I'm facing the issue fixed by [this PR](https://github.com/klarna/brod/pull/392) regarding aborted transactions.

Currently, I'm pulling the dep directly via git and I wonder if there's any chance you can publish brod 3.11 on hex.pm?

Thanks in advance

**Comment by qzhuyan** [comment]
done
