### ISSUE TITLE
Brod Client Status, Consumer Status

### ISSUE THREAD

**Issue by sebasb21** [kafka4beam/brod#411]
Could not find a clear way to interrogate a Client or Consumer to understand it's health. 

I'm looking for some indicator i can poll to see if the consumer have assignments and are "ready" as far as they know to receive messages.

Anyone do anything like this?

Cheers,
Sebastian

**Comment by k32** [comment]
Do you need this information for some business logic, or for monitoring/troubleshooting?

**Comment by sebasb21** [comment]
Health check and monitoring.

**Comment by k32** [comment]
You are right, currently there is no API for getting this information directly from brod, except from `sys:get_state()`, of course. But you can obtain most of the information about assignments and commits from services like Kafka HQ or KastleX, so I would say there isn't too much need for this feature in brod.

**Comment by sebasb21** [comment]
Well that's fine, i was not implying there was a need for a feature. But maybe there was some internal state somewhere that was a good health indicator. Cheers!
