### ISSUE TITLE
Group subscriver v2 configuration

### ISSUE THREAD

**Issue by prabello** [kafka4beam/brod#412]
I'm trying to use the group_subscriber_v2 as described in https://github.com/klarna/brod/blob/master/src/brod_group_subscriber_v2.erl#L133-L169 but couldn't do it

I'm using elixir so I basically created a map with the configurations tried to start it.

My module looks like this:
```
defmodule BrodSample.Consumer do
  def start() do
    group_config = [
      offset_commit_policy: :commit_to_kafka_v2,
      offset_commit_interval_seconds: 5,
      rejoin_delay_seconds: 2,
      reconnect_cool_down_seconds: 10
    ]

    config = [
      client: :kafka_client,
      group_id: "consumer_group",
      topics: ["reviews.reviews"],
      cb_module: __MODULE__,
      group_config: group_config,
      consumer_config: [begin_offset: :earliest]
    ]

    {:ok, _pid} = :brod.start_link_group_subscriber_v2(config)
  end

  def init(_arg, _arg2) do
    {:ok, []}
  end

  def handle_message(message, state) do
    IO.inspect(message, label: "message")
    IO.inspect(state, label: "state")

    {:ok, :ack, state}
  end
end
```
I'm also auto-starting the `:kafka_client` on my config file

any thoughts?

**Comment by k32** [comment]
Hi! Unfortunately, I am not very familiar with Elixir, but it looks like you are creating a proplist, rather than a map (in Erlang terms). What you _probably_ want to use to define `config` term is this: https://hexdocs.pm/elixir/Map.html

**Comment by prabello** [comment]
> Hi! Unfortunately, I am not very familiar with Elixir, but it looks like you are creating a proplist, rather than a map (in Erlang terms). What you _probably_ want to use to define `config` term is this: https://hexdocs.pm/elixir/Map.html

Youre right, solved the issue thanks a lot @k32
