### ISSUE TITLE
Elixir tutorial

### ISSUE THREAD

**Issue by prabello** [kafka4beam/brod#414]
Hey, I've written a small tutorial on how to use `brod`, wondering if its worth to translate it into an example on this repo

If its something y'all would consider, please let me know and I'll try to improve it to be more precise and add the code

Something like an `examples` folder, with the sample Elixir app inside.

Thanks
The tutorial -> https://github.com/prabello/brod_sample/blob/master/README.md

**Comment by mikpe** [comment]
Why not?  I suggest putting it in contrib/examples/

**Comment by prabello** [comment]
Sorry the delay, made an MR https://github.com/klarna/brod/pull/425, I was waiting to have more time to work on it, but I think it makes more sense to evolve it instead of waiting until I have the time i want
