### ISSUE TITLE
Producer processes hold too much memory

### ISSUE THREAD

**Issue by pouriya** [kafka4beam/brod#418]
Hi. After finishing load test, our monitoring tool shows that Erlang holds ~1GB memory (it was ~60MB before test).

![Screenshot_2020-09-07 RunTime - Grafana](https://user-images.githubusercontent.com/20663776/92353559-dafeb200-f0f5-11ea-8a3b-d23b62c0866b.png)  

So I started to find out what is going on. I made a sorted list which contains all processes with their memory:  
```erlang
lists:reverse(lists:keysort(2, recon_lib:proc_attrs(memory))).
[
 {<8374.450.0>,56195916,[{current_function,{gen_server,loop,7}},{initial_call,{proc_lib,init_p,5}}]},
 {<8374.443.0>,56194756,[{current_function,{gen_server,loop,7}},{initial_call,{proc_lib,init_p,5}}]},
 {<8374.442.0>,56193100,[{current_function,{gen_server,loop,7}},{initial_call,{proc_lib,init_p,5}}]},
 {<8374.428.0>,56192956,[{current_function,{gen_server,loop,7}},{initial_call,{proc_lib,init_p,5}}]},
 {<8374.445.0>,56192420,[{current_function,{gen_server,loop,7}},{initial_call,{proc_lib,init_p,5}}]},
 {<8374.439.0>,56187308,[{current_function,{gen_server,loop,7}},{initial_call,{proc_lib,init_p,5}}]},
 {<8374.430.0>,56183068,[{current_function,{gen_server,loop,7}},{initial_call,{proc_lib,init_p,5}}]},
 {<8374.441.0>,56182628,[{current_function,{gen_server,loop,7}},{initial_call,{proc_lib,init_p,5}}]},
 {<8374.453.0>,56181980,[{current_function,{gen_server,loop,7}},{initial_call,{proc_lib,init_p,5}}]},
 {<8374.433.0>,47941036,[{current_function,{gen_server,loop,7}},{initial_call,{proc_lib,init_p,5}}]},
 {<8374.434.0>,47939852,[{current_function,{gen_server,loop,7}},{initial_call,{proc_lib,init_p,5}}]},
 {<8374.432.0>,47937788,[{current_function,{gen_server,loop,7}},{initial_call,{proc_lib,init_p,5}}]},
 {<8374.424.0>,47932892,[{current_function,{gen_server,loop,7}},{initial_call,{proc_lib,init_p,5}}]},
 {<8374.444.0>,47931948,[{current_function,{gen_server,loop,7}},{initial_call,{proc_lib,init_p,5}}]},
 {<8374.451.0>,47928116,[{current_function,{gen_server,loop,7}},{initial_call,{proc_lib,init_p,5}}]},
 {<8374.436.0>,41064148,[{current_function,{gen_server,loop,7}},{initial_call,{proc_lib,init_p,5}}]},
 {<8374.425.0>,32781212,[{current_function,{gen_server,loop,7}},{initial_call,{proc_lib,init_p,5}}]},
 {<8374.452.0>,24853172,[{current_function,{gen_server,loop,7}},{initial_call,{proc_lib,init_p,5}}]},
 {<8374.86.0>,7637372,[alarm_handler,{current_function,{gen_event,fetch_msg,6}},{initial_call,{proc_lib,init_p,5}}]}
 % ...
]
```
So I tried by running:  
```erlang
erlang:process_info(<8374.443.0>).
[{current_function,{gen_server,loop,7}},
 {initial_call,{proc_lib,init_p,5}},
 {status,waiting},
 {message_queue_len,0},
 {links,[<8374.417.0>]},
 {dictionary,[{'$initial_call',{brod_producer,init,1}},<8374.114.0>]}]},
 {trap_exit,true},
 {error_handler,error_handler},
 {priority,normal},
 {group_leader,<8374.113.0>},
 {total_heap_size,7024251},
 {heap_size,833026},
 {stack_size,11},
 {reductions,23058499},
 {garbage_collection,[{max_heap_size,#{error_logger => true,kill => true,size => 0}},
                      {min_bin_vheap_size,46422},
                      {min_heap_size,233},
                      {fullsweep_after,10},
                      {minor_gcs,3}]},
 {suspending,[]}]
```
And I figured it out that except `alarm_handler` all above processes are running `brod_producer` code! So I thought it would be some buffer in its state and tried with:  
```erlang
sys:get_state(<8374.443.0>).
{state,<8374.405.0>,
       <<"topic_name">>,
       25,undefined,undefined,
       {buf,256,1,1048576,3,0,0,#Fun<brod_producer.1.19472292>,0,0,
            {[],[]},
            {[],[]},
            []},
       500,undefined,undefined,
       {resolved,5}}
```
So you can see that buffer is empty. Finally I tried with garbage collector:  
```erlang 
erlang:garbage_collect(<8374.443.0>).
true

erlang:process_info(<8374.443.0>).
[{current_function,{gen_server,loop,7}},
 {initial_call,{proc_lib,init_p,5}},
 {status,waiting},
 {message_queue_len,0},
 {links,[<8374.417.0>]},
 {dictionary,[{'$initial_call',{brod_producer,init,1}},<8374.114.0>]}]},
 {trap_exit,true},
 {error_handler,error_handler},
 {priority,normal},
 {group_leader,<8374.113.0>},
 {total_heap_size,233},
 {heap_size,233},
 {stack_size,11},
 {reductions,23151194},
 {garbage_collection,[{max_heap_size,#{error_logger => true,kill => true,size => 0}},
                      {min_bin_vheap_size,46422},
                      {min_heap_size,233},
                      {fullsweep_after,10},
                      {minor_gcs,0}]},
 {suspending,[]}]
```
And monitoring tool shows:  
![Screenshot_2020-09-07 RunTime - Grafana(1)](https://user-images.githubusercontent.com/20663776/92353776-48aade00-f0f6-11ea-8469-61db3c1325d1.png)

### Other information that may help you:  
OS: Linux docker7 4.15.0-115-generic 116-Ubuntu
Runtime: Erlang/OTP 22 with VM arguments `-K true -P 1048576 -pc unicode -A 128 -zdbbl 2048 -spp true -smp auto -env ERL_FULLSWEEP_AFTER 10`
**brod** library version: 3.14.0

**Comment by k32** [comment]
Hi. What kind of payloads do you produce in the test? 

I am no expert on tuning the GC, but it looks like producer processes were actively allocating memory during the test, and after the test finished, they suddenly went into idle state, and didn't perform enough reductions or allocations to trigger GC.

**Comment by mikpe** [comment]
If an Erlang server process simply stops executing (because it receives no further work to perform), then it's normal for it to have a large heap.  Ideally a process should terminate when it's done, or hibernate if it's done for now but is likely to be used again in the future.

**Comment by qzhuyan** [comment]
how many producers you have? how many sockets are opened?
worth check the socket buffer size and also check fragmentation with recon_alloc.
how many schedulers you have?

**Comment by pouriya** [comment]
> What kind of payloads do you produce in the test?  

Encoded dynamic XML (binary) with size ~1024 bytes (~1KB).

> how many producers you have?  

Because I changed partition count in different tests I don't remember exact count. I think it was between 32-64.

> how many schedulers you have?  

32

> worth check the socket buffer size and also check fragmentation with recon_alloc.  

I could not do that at the time but I will.

**Comment by zmstone** [comment]
inactive for quite long. closing it now.
