### ISSUE TITLE
v3.15 won't compile in an Elixir project

### ISSUE THREAD

**Issue by dnsbty** [kafka4beam/brod#424]
When I include brod 3.15 in a project using Elixir 1.11 and OTP 23.1.1, compiling fails with the following output:

```
===> Compiling brod
===> Compiling src/brod_group_member.erl failed
include/brod.hrl:21: can't find include lib "kafka_protocol/include/kpro_public.hrl"; Make sure kafka_protocol is in your app file's 'applications' list

include/brod_int.hrl:21: can't find include lib "kafka_protocol/include/kpro.hrl"; Make sure kafka_protocol is in your app file's 'applications' list

** (Mix) Could not compile dependency :brod, "/Users/dennisbeatty/.asdf/installs/elixir/1.11/.mix/rebar3 bare compile --paths /Users/dennisbeatty/Code/brod_sample/_build/dev/lib/*/ebin" command failed. You can recompile this dependency with "mix deps.compile brod", update it with "mix deps.update brod" or clean it with "mix deps.clean brod"
```

If I revert to brod 3.14 everything works fine. I've looked through the diff between the two tags and nothing really stands out to me as the culprit.

Also I can compile properly if I just use `rebar3 compile` instead of the `rebar3 bare compile --paths _build/dev/lib/*/ebin` like `mix compile` uses. I don't know enough about erlang and rebar to know what that actually means though.

**Comment by dnsbty** [comment]
I don't know if this is helpful, but I ran `DEBUG=1 rebar3 bare compile` and get the following output:

```
===> Evaluating config script "rebar.config.script"
===> Expanded command sequence to be run: []
===> Provider: {default,do}
===> Expanded command sequence to be run: [{default,app_discovery},
                                                  {bare,compile}]
===> Provider: {default,app_discovery}
===> Provider: {bare,compile}
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> Uncaught error: function_clause
===> Stack trace to the error location:
[{string,lexemes_m,
         [undefined,{" "," ",undefined},[]],
         [{file,"string.erl"},{line,1282}]},
 {rebar_prv_bare_compile,do,1,
                         [{file,"/private/var/folders/lk/dw4q4sv179d_ttltjy9mjhj40000gp/T/rebar3-3.11.1/src/rebar_prv_bare_compile.erl"},
                          {line,45}]},
 {rebar_core,do,2,
             [{file,"/private/var/folders/lk/dw4q4sv179d_ttltjy9mjhj40000gp/T/rebar3-3.11.1/src/rebar_core.erl"},
              {line,154}]},
 {rebar_prv_do,do_task,5,
               [{file,"/private/var/folders/lk/dw4q4sv179d_ttltjy9mjhj40000gp/T/rebar3-3.11.1/src/rebar_prv_do.erl"},
                {line,87}]},
 {rebar_core,do,2,
             [{file,"/private/var/folders/lk/dw4q4sv179d_ttltjy9mjhj40000gp/T/rebar3-3.11.1/src/rebar_core.erl"},
              {line,154}]},
 {rebar3,run_aux,2,
         [{file,"/private/var/folders/lk/dw4q4sv179d_ttltjy9mjhj40000gp/T/rebar3-3.11.1/src/rebar3.erl"},
          {line,178}]},
 {rebar3,main,1,
         [{file,"/private/var/folders/lk/dw4q4sv179d_ttltjy9mjhj40000gp/T/rebar3-3.11.1/src/rebar3.erl"},
          {line,66}]},
 {escript,run,2,[{file,"escript.erl"},{line,758}]}]
```

**Comment by k32** [comment]
Here [1] I see that metadata is incorrect. `requirements` field became empty, and `kafka_protocol` dependency and the others got lost. That explains why kafka_protocol wasn't downloaded. On the other hand, the application file is intact, so I assume this is related to the publishing process rather than code changes. I wonder which version of `rebar3` and `hex` plugin were used to publish 3.15. @jesperes ?

[1] https://diff.hex.pm/diff/brod/3.14.0..3.15.0

**Comment by dnsbty** [comment]
Nice find! I was looking at the git diff and didn't see anything there. That makes a lot more sense. And thanks for linking to the Hex diff checker because it let me learn something new today 😄

**Comment by qzhuyan** [comment]
new release 3.15.1 is released on hex.pm

**Comment by jesperes** [comment]
> Here [1] I see that metadata is incorrect. `requirements` field became empty, and `kafka_protocol` dependency and the others got lost. That explains why kafka_protocol wasn't downloaded. On the other hand, the application file is intact, so I assume this is related to the publishing process rather than code changes. I wonder which version of `rebar3` and `hex` plugin were used to publish 3.15. @jesperes ?
> 
> [1] https://diff.hex.pm/diff/brod/3.14.0..3.15.0

I honestly don't know why the "requirements" field became empty; I didn't see it until I had already published the release. Presumably some environmental issue (combination of otp and rebar version, perhaps?)

**Comment by jesperes** [comment]
Now at least I know that the "requirements" fields is actually used, so I'll check it more carefully next time.
