### ISSUE TITLE
Address remarks

### ISSUE THREAD

**Issue by k32** [kafka4beam/brod#438]
@epsylonix commented on this pull request.

Hi @k32, could you please look into these probable issues?

In src/brod_group_subscriber_v2.erl:

>      [TopicPartition|_] ->
-      handle_worker_failure(TopicPartition, Pid, Reason, State)
+      handle_worker_failure(TopicPartition, Pid, Reason, State);
+    _ -> % Other process wants to kill us, supervisor?
+      {stop, shutdown}

this should probably be {stop, shutdown, State}

In src/brod_group_subscriber_v2.erl:

>      [TopicPartition|_] ->
-      handle_worker_failure(TopicPartition, Pid, Reason, State)
+      handle_worker_failure(TopicPartition, Pid, Reason, State);
+    _ -> % Other process wants to kill us, supervisor?

I believe there is a bug here: when a worker is stopped (in terminate_worker), brod_group_subscriber_v2 removes its partition => worker_pid from the state but since it is trapping exits, brod_group_subscriber_v2 will receive a normal exit from that worker later, and then this clause will catch this exit and brod_group_subscriber_v2 will shut down. I believe at this moment any assignments_revoked call would lead to brod_group_subscriber_v2 crash and restart.

There is possibly another issue with the workers termination process:
brod_topic_subscriber is stopped by casting stop and waiting for the 'DOWNmessage (https://github.com/kafka4beam/brod/blob/master/src/brod_topic_subscriber.erl#L256), butbrod_group_subscriber_v2is trapping exits, so it would receiveEXITinstead and noDOWN` message will be sent if I'm not mistaken

**Comment by epsylonix** [comment]
Hi, there was a small PR with a fix for this but it looks like it was lost during the repository migration. I can make it again if needed.
