### ISSUE TITLE
eheap_alloc error when calling exit in brod_producer_buffer.erl

### ISSUE THREAD

**Issue by gonzalobf** [kafka4beam/brod#443]
We found that when kafka is down and `brod_producer.erl` reaches the `reached_max_retries`, this [exit](https://github.com/kafka4beam/brod/blob/master/src/brod_producer_buffer.erl#L304) does  the VM to crash with a eheap_alloc message. The error message shows that the request contains a disproportional number of bytes like`eheap_alloc: Cannot allocate 863825524200 bytes of memory (of type"message").`

When `brod_producer` exits, `gen_server` tries to format the `#state{}` with the buffer data. This can contain thousand of elements and does `gen_server:terminate` to request more memory and crash. 

A solution we found is to create a custom [format_status function](http://erlang.org/doc/man/gen_server.html#Module:format_status-2) in `brod_producer.erl` that replaces the buffer in the state when gen_server call it [here](https://github.com/erlang/otp/blob/master/lib/stdlib/src/gen_server.erl#L1246) with `terminate` Opt.

**Comment by mikpe** [comment]
We recently had major issues with sudden massive memory consumption coinciding with a kafka outage and lots of crash logs from brod, which looks very much like the issue reported here.

**Comment by qzhuyan** [comment]
I am thinking another solution is to limit the max heap size of a process?

**Comment by mikpe** [comment]
> I am thinking another solution is to limit the max heap size of a process?

I think that fixes a symptom rather than the cause. We know that kafka outages cause these pointless crashes and restarts of brod. There is no value in detailed crash reports from them, so why waste time and memory on generating them?

**Comment by gonzalobf** [comment]
It would probably be a good long term solution to move the `brod_producer_buffer` to ets so when it crashes it doesn't get serialized. However, the change would be quite big and it will need to stop the application.
