### ISSUE TITLE
Worker terminating with reason `:normal` after calling `resolve_offset`

### ISSUE THREAD

**Issue by smoes** [kafka4beam/brod#450]
We're using elsa as a wrapper for brod in our Elixir-project. We are facing unexpected behavior when calling brod's `resolve_offset` function. That is, our elsa consumer that operates on the same topic receives an exit signal with reason `:normal`. The exit signal arrives not immediately, but a short time after the call of `resolve_offset`. The consumer works perfectly fine, if we don't call `resolve_offset` on the same topic. 

We tried to narrow down the reason for this and it seems the exit signal is originated somewhere in brod. We weren't able to follow the signal chain entirely, so take this with a grain of salt. 

One thing we noticed is that the following changes in the parameters of `with_conn` stop the unexpected behavior and our consumer doesn't quit after calling `resolve_offset` on the same topic:

https://github.com/kafka4beam/brod/blob/master/src/brod_utils.erl#L156

    %% @doc Resolve timestamp to real offset.
    -spec resolve_offset([endpoint()], topic(), partition(),
                         offset_time(), conn_config(),
                        #{timeout => kpro:int32()}) ->
            {ok, offset()} | {error, any()}.
    resolve_offset(Hosts, Topic, Partition, Time, ConnCfg, Opts) ->
      with_conn(
        % we changed this, as seen in get_metadata
        % kpro:connect_partition_leader(Hosts, ConnCfg, Topic, Partition, Opts),
        Hosts, ConnCfg,
        fun(Pid) -> resolve_offset(Pid, Topic, Partition, Time) end).

Do you have any idea if this is a bug or are we just doing it wrong? 
We really appreciate any hints, since we've already spent days debugging this issue.

**Comment by zmstone** [comment]
hi @smoes this is bug.
we'll have a look and fix.

**Comment by zmstone** [comment]
Hi @smoes 
which version `brod` are you using ?
also, please check which `kafka_protocol` is used too. (pined by mix.lock maybe)

**Comment by smoes** [comment]
We are using 

brod, "3.9.5"
kafka_protocol, "2.3.3"

**Comment by smoes** [comment]
Forgot to mentioned: Tested and works as expected now. Thank you for the very fast fix!
