### ISSUE TITLE
brod_group_coordinator session_timeout_seconds documentation is off

### ISSUE THREAD

**Issue by mjparrott** [kafka4beam/brod#457]
https://github.com/kafka4beam/brod/blob/582f95cf01a1d72334078f0a31b6e6fd22f2051d/src/brod_group_coordinator.erl#L51 says 30 seconds however the documentation at https://github.com/kafka4beam/brod/blob/582f95cf01a1d72334078f0a31b6e6fd22f2051d/src/brod_group_coordinator.erl#L183 says 10 seconds. Not sure what should be the correct one?

**Comment by zmstone** [comment]
will be fixed in #465
