### ISSUE TITLE
Trying to run brod CLI

### ISSUE THREAD

**Issue by lud** [kafka4beam/brod#462]
Hi,
I think I am misunderstanding the docs to properly build the CLI.

Running: ` _build/brod_cli/rel/brod/bin/brod meta -b localhost` as in the docs:

```
Usage: brod [COMMAND] [ARGS]

Commands:

  foreground              Start release with output to stdout
  remote_console          Connect remote shell to running node
  rpc [Mod [Fun [Args]]]] Run apply(Mod, Fun, Args) on running node
  eval [Exprs]            Run expressions on running node

ETC ETC
```

Looks like a regular erlang release.

I see there is a `brod_cli` script: `_build/brod_cli/rel/brod/bin/brod_cli meta -b localhost`

This time it looks like it is better as we are running an escript:

```escript: exception error: undefined function brod:main/1
  in function  escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 ```

But it fails. Same output with `_build/brod_cli/bin/brod_cli`.
  
So, I guess I am missing something, or maybe there is an error in the build?

Thank you

**Comment by lud** [comment]
Well, 

I was trying to build that from a n elixir project dependencies directory. I guess I was missing some files. Sorry to bother you with that.

I will let the issue open if you want to support building the CLI tool from an elixir project, but as far as I am concerned this issue can be closed.

Thank you very much for brod :D

**Comment by zmstone** [comment]
this seem to be an incomplete crash log.

```
  in function  escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
```

the escript  is built from rebar3 with below command:
`rebar3 as brod_cli do compile,escriptize,release`

Not sure how escriptization is done in your mix project?
maybe missing the non 'default' profile rebar dependency (docopt) ?

**Comment by lud** [comment]
I was trying to build from the `<elixir-project>/deps/brod` directoy but it was incomplete. I had to add the docopt and jsone deps indeed. But it did not work. The problem is that basically elixir does not allow to define  `{erl_opts, [{d, build_brod_cli}]}` for a dependency (to my knowledge).

So I cloned the brod repository in a "tools" directory, checked the `3.15.6` tag out, and ran `make brod-cli`. The docopt an jsone are correctly pulled. The crc32cer library is also pulled but it is not found:

```
 ./_build/brod_cli/bin/brod_cli send --topic hello --key lol --value world --partition 0 -b localhost:29092
*** error:{badmatch,
              {error,
                  {producer_down,
                      {undef,
                          [{crc32cer,nif,
```

Same behaviour with `./_build/brod_cli/rel/brod/bin/brod_cli`.

**Comment by zmstone** [comment]
It's because escriptized executable file can not find the nif .so file (`crc32cer_nif.so`).
You can try to export set `NIF_BIN_DIR` environment variable to make it load.
e.g. `export NIF_BIN_DIR=_build/brod_cli/rel/brod/lib/crc32cer-0.1.8/priv`

**Comment by lud** [comment]
It looks like it works @zmstone ! Thank you.

Is there something more I can configure for this value to be set in the release?

**Comment by zmstone** [comment]
I will send a PR to avoid escriptizing it, and change the entrypoint script to a dash script (base on the current script/brod),
and load applications interactively so there should be no need to set environment variables anymore.

**Comment by lud** [comment]
That would be great, thank you!

**Comment by lud** [comment]
Thank you very much @zmstone
