### ISSUE TITLE
Periodic Leaving group, reason: {shutdown,ssl_closed} 

### ISSUE THREAD

**Issue by sebasb21** [kafka4beam/brod#466]
Im getting `Periodic Leaving group, reason: {shutdown,ssl_closed} ` in a periodic manner using the subscriber group consumer.

Im connecting to kafka via ssl, that works fine, the disconnects cadence it's the same as the idle connection timeout on the server. So i guess is server triggered, but connections, i think, should not be idle cause im producing constantly on those topics or at least quicker than 10 minutes (idle connection timeout configured). And also i have the keepalive socket option: 

```
{brod_client_1, 
            [
              {endpoints, [xxxx]}, %% Broker address list
              {reconnect_cool_down_seconds, 10}, %% socket error recovery
              {auto_start_producers, true},
              {extra_sock_opts, [{keepalive, true}]},
              {ssl, [
                {certfile, "xxx"},
                {keyfile, "xxx"},
                {cacertfile, "xxx"}]}
            ]
          }
```

The disconnect is bad enough, but that triggers a rebalancing of partitions, and it's just a waste of processing back and forth every n minutes.

Im using brod 3.15.1 and erlang 23.2.something.

Anyone see anything like this? 

Regards,
Sebastian

**Comment by zmstone** [comment]
Leaving group indicates that it was the consumer group member getting disconnected,
a consumer group coordinator may not always share the tls connection with producers under the same brod client.

The coordinator should send heartbeats (every 5 seconds by default), which should not cause the ssl connection to idle.

Could you provide the full logs at `info` level? including
1. the full timeline for a group member to join, sync, getting assignments etc.
2. the full log lines, including group ID, member ID generation etc

**Comment by sebasb21** [comment]
what you can see here is the app starting up, getting some partitions, after 9~ minutes idle connection timeout kick in, they are configured at 9 min. 

Reconnects, gets assignments and all over again every ~9 mins.....

```
=INFO REPORT==== 20-Jul-2021::14:42:03.208843 ===
Group member (xxxx-consumer-group,coor=<0.1155.0>,cb=<0.1154.0>,generation=303):
elected=false
=INFO REPORT==== 20-Jul-2021::14:42:03.216980 ===
Group member (xxxx-consumer-group,coor=<0.1155.0>,cb=<0.1154.0>,generation=303):
assignments received:
  topic:
    partition=1 begin_offset=214179
    partition=3 begin_offset=212919
    partition=5 begin_offset=208565
    partition=7 begin_offset=208592
=INFO REPORT==== 20-Jul-2021::14:42:03.438844 ===
client brod_client_1 connected to xxxx:24402
=INFO REPORT==== 20-Jul-2021::14:42:04.475538 ===
client brod_client_1 connected to 10.98.5.44:24402
=INFO REPORT==== 20-Jul-2021::14:42:09.740198 ===
client brod_client_1 connected to 10.98.5.91:24402
....
....
....
....
=INFO REPORT==== 20-Jul-2021::14:51:03.278714 ===
Group member (xxxx-consumer-group,coor=<0.1155.0>,cb=<0.1154.0>,generation=303):
Leaving group, reason: {shutdown,ssl_closed}
=INFO REPORT==== 20-Jul-2021::14:51:06.359617 ===
Group member (xxxx-consumer-group,coor=<0.2493.0>,cb=<0.2491.0>,generation=305):
elected=true
=INFO REPORT==== 20-Jul-2021::14:51:06.364785 ===
Group member (xxxx-consumer-group,coor=<0.2493.0>,cb=<0.2491.0>,generation=305):
assignments received:
  topic:
    partition=0 begin_offset=210102
    partition=2 begin_offset=214100
    partition=4 begin_offset=204084
    partition=6 begin_offset=420865
```

**Comment by zmstone** [comment]
How many consumer members are there in the consumer group?
My guess is that one or more members take too long time to respond to assignment revoke.
The assignments_revoked call from coordinator to group subscriber is a gen_server call with infinity timeout.
If the messages are very small, maybe try to consume smaller batches?

Or handle message (set) asynchronously in the hand_message callback.

**Comment by sebasb21** [comment]
So in the example we have 2 consumers, it happens with 1 or 10.

Messages are small and take nothing to process. We do not process messages in batch, although i guess brod is getting them in batches. 

I mean if we change the connection idle timeout to 1 min this happens every minute if we configure 60 minutes (i think its the max in the server config) then it happens every 60 minutes. It really looks like brod is unable to "keep alive" that connection, it seems to have nothing else to do with the processing of messages. This happens even if there are NO messages.

**Comment by zmstone** [comment]
Which Kafka version is it?
It doesn’t make any sense because it’s sending heartbeats (otherwise session timeout).
Can you find anything interesting in kafka logs?

**Comment by sebasb21** [comment]
Maybe its not sending correct heartbeats for ALL the connections, i have no idea how many it is keeping around.

We currently using kafka 2.8.0 previous version of the server had the same behaviour. Server logs show the rebalancing and all that but nothing else. I guess because it is a perfectly sound behaviour IF heartbeats are not getting to the server. 

I haven't traced in depth network or tracing logs anywhere, i hoped someone was seeing the same thing.

**Comment by sebasb21** [comment]
We just finished testing brod 3.16.0 and it seems to fix this! i guess the upgrade to kpro 4 is the key thing? No more disconnects! It is the only change we did......
