### ISSUE TITLE
Compatibility with erlang and kafka versions

### ISSUE THREAD

**Issue by Kwisatx** [kafka4beam/brod#474]
When I upgraded to the latest version of brod, I was getting crashes in [kafka protocol: kpro_compress.erl](https://github.com/kafka4beam/kafka_protocol/commit/a33555a41ed3fe2b091c569385717772197ce706#diff-0c20c2e203fc94f9fbd546248b8f6155930a221e97becf686fa53052731f66edR99) because of a [method introduced in erlang 21.3](https://erlang.org/doc/man/persistent_term.html#get-2), and we were in 21.2.

Obviously we are not running the most recent erlang version, and I'm not asking you to support erlang 21, but it would be useful to have the information of what versions of erlang you explicitly support more readily available (in the README or the changelog for example). You have automatic builds for 22 and up, so just indicating that would probably be enough.
I don't know if this is something most erlang libraries do, but it would have saved me some time ^^.

A subsequent compatibility question, what log.message.format.version is brod compatible with using the latest version of kafka_protocol ? The changelog explicitly states that version 3.0.0 supports version 2.4, how high can we go with version 4.0.1 ?

**Comment by zmstone** [comment]
Hi. Good point, we'll add min OTP version to readme.

The configuration `log.message.format.version` is internal to Kafka, but not exposed to the clients.
What's interfacing the clients is the so called 'magic' byte (a version number) which has not changed since Kafka 1.1
https://kafka.apache.org/28/documentation.html#recordbatch

**Comment by zmstone** [comment]
> The changelog explicitly states that version 3.0.0 supports version 2.4, how high can we go with version 4.0.1

Stating that it supports Kafka 2.4 means that the API schema code is generated based on Kafka 2.4, and the APIs are tested against Kafka 2.4.
However, it does not mean `brod` or `kafka_protocol` may have trouble connecting newer version Kafka.
Kafka still supports the oldest API versions (such as `produce` and `fetch`).

**Comment by Kwisatx** [comment]
Sounds good, thanks for all the answers!
