### ISSUE TITLE
Error fetching Snappyer's "pc" dependency with hex mirror

### ISSUE THREAD

**Issue by matreyes** [kafka4beam/brod#482]
This is a problem with Snappyer, (I comment it here because it doesn't receive issues).

I'm using a HEX_MIRROR and HEX_CDN (env variables) in my elixir project. I have no access to hex.pm for security reasons, so I have to use a mirror (https://hex.pm/docs/mirrors).

"Snappyer" (https://hex.pm/packages/snappyer) fetches "pc" (https://hex.pm/packages/pc) in compile time. So, when compiling, it tries to fetch "pc" from repo.hex.pm (It' doesn't uses mix or rebar config) 

The error:
```
DEBUG=1 mix deps.compile snappyer
===> Hex get_package request failed: {error,
                                      {failed_connect,
                                       [{to_address,{"repo.hex.pm",443}},
                                        {inet,[inet],nxdomain}]}}
```

Sorry for not creating a PR, but I've no experience with rebar, so I have no idea how it's fetching the dependencies.

**Comment by matreyes** [comment]
As you can see, snappy-erlang-nif has removed the dependency
https://github.com/skunkwerks/snappy-erlang-nif/commit/717918fe4c2951fe34fe19feccdf3b472369cf1d

**Comment by zmstone** [comment]
`nxdomain` error seem to be `mix` command, or the mirroring to blame.
does it work OK if you test the build in a network environment where you don't need the hex mirror ?

**Comment by zmstone** [comment]
I had a look at the code.
it's essentially calling gen_tcp at the very bottom of the call stack where the `nxdomain` error returned.
e.g.
```
1> gen_tcp:connect("no-such-host-repo.hex.pm", 443, [], 5000).
{error,nxdomain}
2> gen_tcp:connect("repo.hex.pm", 443, [], 5000).
{ok,#Port<0.7>}
```
so it's likely that the mirror config is not taking effect for rebar3

**Comment by zmstone** [comment]
you can maybe try this:
```
cd /path/to/snappyer/source_code/
export DIAGNOSTIC=1
export HEX_CDN=".........your mirror. ..."
rm -rf _build
rebar3 compile
```

**Comment by zmstone** [comment]
> As you can see, snappy-erlang-nif has removed the dependency [skunkwerks/snappy-erlang-nif@717918f](https://github.com/skunkwerks/snappy-erlang-nif/commit/717918fe4c2951fe34fe19feccdf3b472369cf1d)

I'm not sure what the `enc` executable is.

**Comment by matreyes** [comment]
> > As you can see, snappy-erlang-nif has removed the dependency [skunkwerks/snappy-erlang-nif@717918f](https://github.com/skunkwerks/snappy-erlang-nif/commit/717918fe4c2951fe34fe19feccdf3b472369cf1d)
> 
> I'm not sure what the `enc` executable is.

Uhhh .. that's dangerous..

**Comment by zmstone** [comment]
> > > As you can see, snappy-erlang-nif has removed the dependency [skunkwerks/snappy-erlang-nif@717918f](https://github.com/skunkwerks/snappy-erlang-nif/commit/717918fe4c2951fe34fe19feccdf3b472369cf1d)
> > 
> > 
> > I'm not sure what the `enc` executable is.
> 
> Uhhh .. that's dangerous..

not necessarily dangerous. 
just that I need to know more about it, then I can start reasoning if it worth doing the same.

**Comment by matreyes** [comment]
oh.. compiling directly from rebar3 accepted the HEX_CDN value, but through mix, it seems that it's overwriting the value.
I will check with the hex team. Thanks (again) @zmstone !
