### ISSUE TITLE
Best way to reliably connect clients for producing?

### ISSUE THREAD

**Issue by sdball** [kafka4beam/brod#49]
Hello!

If I create a bunch of separate processes using brod (in a riak post-commit hook specifically) I'm finding the `start_link_client` calls affect each other and I start getting `{error,{already_started, <PID>}}` responses.

I've tried simply using the PID from the error for the calls to produce, but then I get `{error,{producer_down,shutdown}}` when trying to produce to the PID. Presumably because the other process that started that connection is wrapping up. I get the same behavior if I give `start_link_client` an atom name and use that instead of the PID.

In this case I'm using only producing to Kafka. From what I see in the code it looks like the `already_started` response is from preparing for consumers. If that's right, is there a better way that I should be prepping a link for producing?

If not, should I be watching for the `producer_down` responses and trying to start a new client and producer in response?

**Comment by id** [comment]
Normally you call start_link_client only once when a node starts up and then either use the Pid or start it with atom and use that atom in 'produce' calls from any process in your application.

Is there any special reason why you would need to open a separate connection for every process?

**Comment by sdball** [comment]
It could be my lack of understanding around riak post-commit hooks. Currently my post-commit hook from Riak connects to Kafka and publishes the message. Riak post-commit hooks are run asynchronously in separate processes and each given the Riak object just written.

http://docs.basho.com/riak/1.2.1/references/appendices/concepts/Commit-Hooks/#Post-Commit-Hooks

I tried reusing the same PID (and also tried a common atom) and got the `producer_down` errors. I'm guessing those are because the post-commit hook that first made the connection is closing itself down.

As far as I know there is no higher level where I can setup the Kafka connection, but I can investigate.

Right now I've got this "working" in development by randomizing the client name. It's as hackish as it sounds. :-)

**Comment by id** [comment]
If you call start_link_client within the hook itself than it's explainable. I guess a hook process terminates when your callback is done and of course makes brod_client to terminate too since it was linked.

Is it possible to add brod client configuration (example in README) in sys.config for the node and add brod application to the start list so that brod starts a client itself? Then just use client name in produce calls in the hook callback and don't start_link_client there.

**Comment by id** [comment]
If that is not possible, alternative "hackish" way would be to 1) Check if a process with name "my_brod_client" (for example) exists 2) If yes, take the pid and call brod:produce with that pid 3) If not, call brod:start_link_client and unlink, then 2).

**Comment by sdball** [comment]
Thanks! I'll give using a config a try. The Riak post-commit docs are rather light on anything beyond a simple function, but hopefully I can get it all tied together. :sunglasses:

**Comment by id** [comment]
Correction: add also {auto_start_producers, true} in client config section along with 'endpoints'.

**Comment by sdball** [comment]
Thanks for the ideas! I can't find a configuration piece to hook in the brod configuration per Riak node, but I'm still investigating that.

Reusing the process or PID runs into problems because one hook process will try to produce at the same time another one is shutting it down. So some of the hooks get `{error,{producer_down,shutdown}}}` after checking that the process is registered but the process is shutting down before the produce to it.

At this point I don't think this is brod's issue. I'll be investigating how to maintain a connection for the post-commit hooks from some processes external to the hooks themselves.

**Comment by id** [comment]
@sdball take a look at 2.1-dev branch. We've changed API for starting clients, now you just tell the supervisor to do that.
You can try this in your handler:

```
{ok, _} = application:ensure_all_started(brod),
brod:start_client([{"kafka.int.net", 9092}], riak_handler), % ok or {error, already_started} should both be considered as 'ok'
brod:produce_sync(riak_handler, ...).
```

**Comment by sdball** [comment]
Thanks @id, that looks awesome!

Sorry I meant to circle back around here. We have a prototype (this is all still coming together) solution working where we pass `-s brod` as a Riak command line option. That tells it to call `brod:start()` when Riak itself is starting and nicely uses the brod configuration that it finds in Riak's app configuration.

I'm in the midst of making my own OTP process that will have brod as part of its dependencies. This new interface might be a useful safeguard. :+1:

**Comment by id** [comment]
Awesome!
