### ISSUE TITLE
Tag current master code 

### ISSUE THREAD

**Issue by vikas15bhardwaj** [kafka4beam/brod#493]
It looks like master code is using `kafka_protocol` version 4.0.3 but tagged 3.16.1 version is still using 4.0.1. Can we tag a release of brod main.
We are currently overriding `kafka_protocol` version to 4.0.2 because 4.0.1 has an issue with kerberos auth. This override though causes issue in publishing hex packages.

It would be great, if we can tag it.

**Comment by zmstone** [comment]
Hi @vikas15bhardwaj 

3.16.2 has been tagged and published to hex.pm
https://github.com/kafka4beam/brod/releases/tag/3.16.2

**Comment by vikas15bhardwaj** [comment]
Thank you @zmstone
