### ISSUE TITLE
Flapping Common Tests

### ISSUE THREAD

**Issue by spencerdcarlson** [kafka4beam/brod#504]
* It seems to be the `t_restart_previous_*` test cases.

Example: `t_restart_previous_producers`
* Running a specific flapping test in isolation multiple times does not reproduce the issue.
  ```bash
  rebar3 ct --suite=test/brod_client_SUITE --case t_restart_previous_producers --repeat 100
  All 1 tests passed. (100 times)
  ```
* Running the suite that contains the flapping test can occasionally reproduce the issue.
  ```bash
  rebar3 ct --suite=test/brod_client_SUITE --repeat 10
  Failed 1 tests. Passed 13 tests. (2 times)
  All 14 tests passed. (8 times)
  ===> Failures occurred running tests: 2
  ```

**Stacktrace**
```bash
{{badmatch,{error,{producer_not_found,<<"brod-client-SUITE-topic">>}}},
 [{brod_client_SUITE,t_restart_previous_producers,1,
                     [{file,"/Users/sdc/code/sdc/brod/test/brod_client_SUITE.erl"},
                      {line,255}]},
  {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1783}]},
  {test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1292}]},
  {test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,1224}]}]}
```

**Comment by spencerdcarlson** [comment]
This _seems_ like the race condition between shutting down the producer or consumer and the subsequent call to start it.

* If I add a half second sleep after the call to `brod_client:stop_producer/2` ([L253-L254](https://github.com/kafka4beam/brod/blob/master/test/brod_client_SUITE.erl#L253-L254)) and `brod_client:stop_consumer/2` ([L269-L270](https://github.com/kafka4beam/brod/blob/master/test/brod_client_SUITE.erl#L269-L270)) I can run the SUITE 100 times with no flapping errors.
  ```erlang
  t_restart_previous_producers(Config) when is_list(Config) ->
    Client = t_restart_previous_producers,
    Topic = ?TOPIC,
    ok = start_client(?HOSTS, Client),
    ok = brod:start_producer(Client, Topic, []),
    ok = brod_client:stop_producer(Client, Topic),
    timer:sleep(500), %% Not a valid solution, just identifying the issue.
    ?assertEqual(ok, brod:start_producer(Client, Topic, [])),
    {ok, Pid} = brod_client:get_producer(Client, Topic, 0),
    ?assertEqual(true, erlang:is_process_alive(Pid)),
    ok.
  ```
  ```bash
  rebar3 ct --suite=test/brod_client_SUITE --repeat 100
  # With the `timer:sleep(500)` there are no errors. 
  ```

* When a test has an error, the call to `brod:start_producer/3` or `brod:start_consumer/3` actually falls into the ` %% already started` clause ([producer](https://github.com/kafka4beam/brod/blob/master/src/brod_client.erl#L168), [consumer](https://github.com/kafka4beam/brod/blob/master/src/brod_client.erl#L188)), meaning that the even though stop was just called, the process is somehow currently alive.

It looks like tests are being run synchronously and ordered since there are no groups. There is only 1 call to stop producer and consumer in all tests, so I don't how another test could be starting it. That seems to rule out a possible race condition across multiple tests.

It seems that there must be a race condition between the call to stop a producer/consumer and then immediately start it. The stop code looks like it is synchronous executing `supervisor3:terminate_child/2` and `supervisor3:delete_child/2`. I don't know how it would be possible for `brod_client:stop_producer/2` to return and the process not be fully shutdown before the next line in the test case executes ` brod:start_producer/3` but that seems like what is happening. 

Start is getting called while the pid is still terminating so we see "already started" and then it shuts down and `brod:get_producer/3` fails with `{error,{producer_not_found,<<"brod-client-SUITE-topic">>}}`

I am wondering if the issues is `brod_client:get_partition_worker/2` is returning that the worker is alive when it really is not, which means that `safe_gen_call(Client, {start_producer, TopicName, ProducerConfig}, infinity);` never gets executed in `brod:start_producer/3`

**Comment by spencerdcarlson** [comment]
I am fairly confident that I have identified the issue to be that the ets lookup that happens 
in [brod_client: lookup_partition_worker/3](https://github.com/kafka4beam/brod/blob/master/src/brod_client.erl#L437-L455) can return the pid of a process that is no longer alive 
or is in the process of being shut down. 

Here is an example:
```erlang
%% Eventually calls supervisor3:terminate_child/2 
%% and supervisor3:delete_child/2 for partition worker.
ok = brod_client:stop_producer(Client, Topic), 

%% Only starts the partition worker if it isn't already running.
%% Sometimes the lookup in ets returns the the partition worker pid even after the child has been terminated, 
%% so the call to `brod:start_producer/3` does not attempt to start the partition worker.
brod:start_producer(Client, Topic, []),

%% Fails because by this time, the ets calls to locate returns [].
brod_client:get_producer(Client, Topic, 0).
```

I'm not 100% sure what the fix should be. Do we need to rethink the lookup logic for finding a partition worker?

Should we change [brod_client:deregister_producer/consumer](https://github.com/kafka4beam/brod/blob/master/src/brod_client.erl#L264) from cast to call or safe_gen_call?

**Comment by zmstone** [comment]
The deregister can not be a sync call without more changes as it would become a dead loop?
The client process will eventually loop back to one or more (for each partition) gen_call to self.

**Comment by zmstone** [comment]
>   ```erlang
>   t_restart_previous_producers(Config) when is_list(Config) ->
>     Client = t_restart_previous_producers,
>     Topic = ?TOPIC,
>     ok = start_client(?HOSTS, Client),
>     ok = brod:start_producer(Client, Topic, []),
>     ok = brod_client:stop_producer(Client, Topic),
>     timer:sleep(500), %% Not a valid solution, just identifying the issue.
>     ?assertEqual(ok, brod:start_producer(Client, Topic, [])),
>     {ok, Pid} = brod_client:get_producer(Client, Topic, 0),
>     ?assertEqual(true, erlang:is_process_alive(Pid)),
>     ok.
>   ```

for this test, since all the deregister messages are already sent to client’s mailbox, we can make one gen call (any call should do) to the client process, by the time the call returns, all casts should have been handled

**Comment by spencerdcarlson** [comment]
What do you think about about adding it internally so all clients are safe from a race condition -- https://github.com/kafka4beam/brod/pull/505
