### ISSUE TITLE
Enable SASL Handshake

### ISSUE THREAD

**Issue by zavndw** [kafka4beam/brod#516]
how to enable request Sasl Handshake to kafka?
I'm use example client https://github.com/kafka4beam/brod#other-api-to-play-withinspect-kafka

**Comment by zmstone** [comment]
Hi
Client config is explained here:
https://github.com/kafka4beam/brod#authentication-support
Let us know if it’s not clear enough.

**Comment by zavndw** [comment]
> Hi Client config is explained here: https://github.com/kafka4beam/brod#authentication-support Let us know if it’s not clear enough.


I am using config:
`config :brod,
  [
    clients: [
      kafka_client: [
        auto_start_producers: true,
        endpoints: [{'demo.office.brod', 9092}],
        default_producer_config: [max_retries: 60, retry_backoff_ms: 500],
        ssl: false,
        sasl: {:plain, "alice",  "alice-secret"}
      ]
    ]
  ]`

in the logs kafka "Unexpected Kafka request of type METADATA during SASL handshake"
using kafkacat i checked the kafka configuration is correct (kafkacat -b demo.office.brod:9092 -X security.protocol=SASL_PLAINTEXT -X sasl.mechanisms=PLAIN -X sasl.username=admin -X sasl.password=admin-secret -L
)

**Comment by zmstone** [comment]
Hi @zavndw 
Which Kafka version are you testing against ?

`Unexpected Kafka request of type METADATA during SASL handshake`
This message implies `brod` sent metadata request before finishing SASL handshake which is odd.
Could you try to trace this code, see if it actually performed SASL auth.
https://github.com/kafka4beam/kafka_protocol/blob/7147d6e16652b9b1c39758250bdf93ee934ec706/src/kpro_connection.erl#L239-L241

it should call into this clause:
https://github.com/kafka4beam/kafka_protocol/blob/7147d6e16652b9b1c39758250bdf93ee934ec706/src/kpro_sasl.erl#L45

**Comment by zavndw** [comment]
> Hi @zavndw Which Kafka version are you testing against ?
> 
> `Unexpected Kafka request of type METADATA during SASL handshake` This message implies `brod` sent metadata request before finishing SASL handshake which is odd. Could you try to trace this code, see if it actually performed SASL auth. https://github.com/kafka4beam/kafka_protocol/blob/7147d6e16652b9b1c39758250bdf93ee934ec706/src/kpro_connection.erl#L239-L241

2.13-2.8.1 version. I try trace code

**Comment by anoskov** [comment]
@zmstone Hello! I'm @zavndw's colleague. Thanks for reply. I guess we have a problem because we use prestart hook which checks connection to kafka using `:brod.get_metadata/1` but it doesn't pass SASL option. I'll try `:brod.get_metadata/3` for it

**Comment by anoskov** [comment]
Hello. With :brod.get_metadata/3 and passing SASL opts to it everything works fine

**Comment by zavndw** [comment]
@zmstone thanks for your help
