### ISSUE TITLE
brod:fetch获取的kafka记录不完整

### ISSUE THREAD

**Issue by tanwen321** [kafka4beam/brod#521]
同一个kafka的topic，同一个分区
当我用offset为590438967的时候brod:fetch获取只能拿到这个offset的数据
当我用offset为590438968的时候brod:fetch获取能拿到正常数据
具体的情况请查看附件~~
![image](https://user-images.githubusercontent.com/9924105/181675178-fbdd2609-70bc-4180-a5d8-a79e26a34b8c.png)

**Comment by zmstone** [comment]
Could be that message `590438967` is large enough to fill up the entire response batch ?
Anyway, `brod` sends the request, and it's Kafka who decides how many messages to return in the response batch.
e.g. if offset `590438967` happens to be the last message in a index block in Kafka, or if it's the last message in a Kafka segment file, then it's probably only one message returned for this request.

BTW. The returned offset in the ok-tuple is the current high-watermark offset, but not necessary related to the current batch.

I'm closing this issue as I believe this behaviour is not something `brod` has control over.
