### ISSUE TITLE
How to properly disable the clients in tests

### ISSUE THREAD

**Issue by yordis** [kafka4beam/brod#536]
I have the following in my `config/config.exs` file (Elixir Umbrella app)

```elixir
# config/config.exs
config :brod, clients: [tm_client: [auto_start_producers: true]]
```

And the following in my `config/test.exs` file
```elixir
# config/test.exs
config :brod,
  clients: [
    tm_client: [
      auto_start_producers: false, # NOTICE HERE
      endpoints: [{"localhost", 9092}]
    ]
  ]
```

Notice that I disabled the client using `auto_start_producers: false` but I keep getting the following in my tests:

```
18:12:24.579 [error] GenServer :tm_client terminating
** (stop) [{{"localhost", 9092}, {:timeout, [{:kpro_connection, :connect, 4, [file: '/hmbradley_umbrella/deps/kafka_protocol/src/kpro_connection.erl', line: 208]}, {:kpro_connection, :init, 4, [file: '/hmbradley_umbrella/deps/kafka_protocol/src/kpro_connection.erl', line: 170]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}]
    (brod 3.16.4) /hmbradley_umbrella/deps/brod/src/brod_client.erl:570: :brod_client.ensure_metadata_connection/1
    (brod 3.16.4) /hmbradley_umbrella/deps/brod/src/brod_client.erl:298: :brod_client.handle_info/2
    (stdlib 3.17.2) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17.2) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: :init
```

Thank you in advance.

**Comment by zmstone** [comment]
Having clients configured will lead to client auto start.
A `brod_client` is a process which manages the TCP connections and also manages producers and consumers which make use of the connections.
`auto_start_producers` only stops from auto-starting the producer, but does not stop `brod_client`  from connecting the configured Kafka endpoints (it needs to connect for metadata refresh etc).

If you do not wish to have clients started automatically, you can simply avoid setting the `clients` config.
And call `brod:start_client` on demand.

**Comment by yordis** [comment]
@zmstone roger! Thank you for the feedback.

For others and my future self, what that means is that I should remove the `clients` from my `config/config.exs` and them explicitly to `config/dev.exs` and `config/prod.exs`
