### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by VitorTrin** [kafka4beam/brod#560]
Gcc 13 is becoming more common, and using gcc 13 with the current version of `brod` that uses an oudated version of [snappyer](https://github.com/zmstone/snappyer) is broke. The fix is already in the master, it just needs to be in a release

**Comment by Coffei** [comment]
@zmstone or somebody else, can we please get a release? Gcc 13 is also included in Fedora 38 which is quite popular.

**Comment by angordeyev** [comment]
@zmstone Are there any issues stopping publishing the new release? I could help with that, I could not build on Arch Linux because of GCC 13 either.

**Comment by zmstone** [comment]
Sorry, did not notice this.
Released in September 2023 `3.17.0` has snappyer upgraded.
