### ISSUE TITLE
brod_demo_group_subscriber_loc has error in kafka 0.8.2 

### ISSUE THREAD

**Issue by jolsnow** [kafka4beam/brod#57]
Hey, when i use brod (new, 2.0) as a consumer client to connect kafka server(0.8.2) as brod_demo_group_subscriber_loc.erl/brod_demo_group_subscriber_koc.erl

the kafka server has error :

[2016-04-25 16:01:38,744] ERROR Closing socket for /127.0.0.1 because of error (kafka.network.Processor)
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'topics': java.nio.BufferUnderflowException
    at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:66)
    at org.apache.kafka.common.requests.JoinGroupRequest.parse(JoinGroupRequest.java:85)
    at kafka.api.JoinGroupRequestAndHeader$.readFrom(JoinGroupRequestAndHeader.scala:29)
    at kafka.api.RequestKeys$$anonfun$12.apply(RequestKeys.scala:50)
    at kafka.api.RequestKeys$$anonfun$12.apply(RequestKeys.scala:50)
    at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
    at kafka.network.Processor.read(SocketServer.scala:450)
    at kafka.network.Processor.run(SocketServer.scala:340)

and the client has error:

=INFO REPORT==== 25-Apr-2016::16:01:36 ===
group controller (groupId=brod-demo-group-subscriber-loc-group-id,memberId=,generation=0,pid=<5384.23225.2>):
re-joining group, reason:{sock_down,tcp_closed}*\* at node brod@127.0.0.1 **

=INFO REPORT==== 25-Apr-2016::16:01:36 ===
group controller (groupId=brod-demo-group-subscriber-loc-group-id,memberId=,generation=0,pid=<5384.23223.2>):
connected to group coordinator localhost:9092*\* at node brod@127.0.0.1 **

=INFO REPORT==== 25-Apr-2016::16:01:36 ===
group controller (groupId=brod-demo-group-subscriber-loc-group-id,memberId=,generation=0,pid=<5384.23223.2>):
failed to join group
reason:{sock_down,tcp_closed}*\* at node brod@127.0.0.1 **

i don`t know the kafka protocol details so i don`t know what mistake i make.
sorry for my poor english , if have some thing confusion we can communicate by chinese @ zaiming 

Thanks

**Comment by zmstone** [comment]
Hi Thanks for the report.
It seems that Kafka upgraded JoinGroupRequest from 0.8 version to 0.9 version without even bumping the API version number.

0.8.2

```
public static Schema JOIN_GROUP_REQUEST_V0 = new Schema(new Field("group_id",
                                                                  STRING,
                                                                  "The consumer group id."),
                                                        new Field("session_timeout",
                                                                  INT32,
                                                                  "The coordinator considers the consumer dead if it receives no heartbeat after this timeout in ms."),
                                                        new Field("topics",
                                                                  new ArrayOf(STRING),
                                                                  "An array of topics to subscribe to."),
                                                        new Field("consumer_id",
                                                                  STRING,
                                                                  "The assigned consumer id or an empty string for a new consumer."),
                                                        new Field("partition_assignment_strategy",
                                                                  STRING,
                                                                  "The strategy for the coordinator to assign partitions."));
```

0.9.0

```
public static final Schema JOIN_GROUP_REQUEST_V0 = new Schema(new Field("group_id",
                                                                        STRING,
                                                                        "The group id."),
                                                              new Field("session_timeout",
                                                                        INT32,
                                                                        "The coordinator considers the consumer dead if it receives no heartbeat after this timeout in ms."),
                                                              new Field("member_id",
                                                                        STRING,
                                                                        "The assigned consumer id or an empty string for a new consumer."),
                                                              new Field("protocol_type",
                                                                        STRING,
                                                                        "Unique name for class of protocols implemented by group"),
                                                              new Field("group_protocols",
                                                                        new ArrayOf(JOIN_GROUP_REQUEST_PROTOCOL_V0),
                                                                        "List of protocols that the member supports"));
```

I don't really have a nice solution on top of my head.
Will think more about it.

**Comment by jolsnow** [comment]
Thank you for positive response, i will study the protocol together to find the reason about this issue.

**Comment by zmstone** [comment]
The JOIN_GROUP_REQUEST_V0 schema code is there in 0.8 code base, but it is never used until 0.9.

0.8 group management is done by directly connecting to zookeeper.
I do not think it's worth the effort to support 0.8 group management in brod.

closing this issue.
