### ISSUE TITLE
Does it support jks file sert?

### ISSUE THREAD

**Issue by Vkutovoy92** [kafka4beam/brod#579]
1. Brod 3.17.1
2. Erlang 23
```
                {ssl, [
                    {cacertfile, "config/production/AFSTS.jks"}
            ]}
```

How to make it works?
`
{tls_alert,{unexpected_message,"TLS client: In state connection at tls_record.erl:558 generated CLIENT ALERT: Fatal - Unexpected Message\n {unsupported_record_type,0}"}}}
TLS client: In state connection at tls_record.erl:558 generated CLIENT ALERT: Fatal - Unexpected Message, - {unsupported_record_type,0}`

**Comment by mikpe** [comment]
I think this is a question for the OTP team rather than users of TLS like brod.

**Comment by Vkutovoy92** [comment]
> I think this is a question for the OTP team rather than users of TLS like brod.

Okay, but in general how to pass ssl cert params to driver? All possible options.

**Comment by zmstone** [comment]
I believe the best reference for "all possible options" for a developer is this: https://www.erlang.org/doc/man/ssl#type-tls_client_option
