### ISSUE TITLE
Add CRC field to #kafka_message{} 

### ISSUE THREAD

**Issue by ates** [kafka4beam/brod#59]
It would be great to have that field in #kafka_message{}, is it possible?

**Comment by zmstone** [comment]
it is possible.
but, do you have a use case example ?
i.e. why would upper level application care about a message checksum ?

**Comment by ates** [comment]
It's a very specific case and I believe it's related only (maybe) to our application.

I want to use CRC as a fingerprint of the message for additional type of authorization.

It's hard to explain more detailed without the whole description of our system.
But I hope that field addition should not impact the brod and may be useful for someone else.

**Comment by zmstone** [comment]
interesting use case, i'd love to know how it works if you are willing to share.

Add one more field to kafka_message record should not impact anything.
(except for the users who's doing hot swapping upgrades,
i.e. some queued messages might get badrecord error after new beam is loaded)

I'll look into this
