### ISSUE TITLE
Sending tombstones with brod

### ISSUE THREAD

**Issue by alexanderttalvarez** [kafka4beam/brod#592]
I'm trying to send a [tombstone](https://medium.com/@damienthomlutz/deleting-records-in-kafka-aka-tombstones-651114655a16) message with brod, but looks like it's not supported.

For example:
`:brod.produce_sync(:client, "my-topic", :hash, ["my-key"], nil)`

But I get an error:
```
1st argument: not an iodata term

    (erts 14.2.1) :erlang.iolist_to_binary(nil)
```

Is there any way of doing so?

Thank you!

**Comment by zmstone** [comment]
try atom `:undefined` or empty binary-string `""`
