### ISSUE TITLE
Very little high-level documentation

### ISSUE THREAD

**Issue by Shnatsel** [kafka4beam/brod#6]
I'm evaluating whether I can use a range of Kafka clients for a project I'm developing, and README.md doesn't answer the following basic questions about Brod:
- Are these bindings to a Java client or an independent implementation? (answered by looking at all of the code)
- Does it require ZooKeeper (locally or at all)?
- Does it support the high-level consumer or it's an equivalent of the Simple Comsumer? (Turns out simple only because there is an issue for that)
- Does it support message batching? (If not I could probably contribute it, sounds simple to implement)

**Comment by zmstone** [comment]
Hi Shnatsel
- independent implementation
- it does not require any direct connection to zookeeper now, (and not in the future either)
- no, as you already noticed, that's the plan
- yes

BTW, There is a heavy (internal logic) refactoring on going.

**Comment by Shnatsel** [comment]
Thanks for the quick reply!

I imagine ZooKeeper is still required somewhere in the Kafka cluster to propagate offset information between potential leaders for a partition, right? It's probably a n00b question, but Kafka internals can be hard to grasp at first.

Will the refactoring affect external APIs and error handing? Since I'm familiarising myself with the code anyway, do you need any help with the refactoring?

**Comment by zmstone** [comment]
Yes, kafka needs connection to zookeeper for various of reasons, but not the clients.
Before 0.8.2 consumer groups commit their offsets to zookeeper, Brod does/will not support it.
The refactoring will not affect existing APIs or at least will keep the old ones working but make them deprecated. Same for error handling, internals might be different, but should be transparent to callers.

Thanks for offering help, I will check with @id see if we can push the dev branch to github.

**Comment by id** [comment]
Thx @zmstone! Will push my dev branch during the next week.

**Comment by zmstone** [comment]
@Shnatsel, we ended up developing 2.0 (i.e. non backward compatible changes, at least for producer APIs), see 2.0-dev branch

**Comment by Shnatsel** [comment]
Thanks for the heads-up!

I'll need persistence for the producer in my application, i.e. messages not yet delivered should be stored on disk and the queue should persist even after a reboot. As far as I can tell Brod doesn't support this yet, so I'll have to implement it, preferably in Brod itself. Any tips how to go about this would be appreciated.

**Comment by zmstone** [comment]
I believe we have exactly the same requirement in my team!

However I think we should keep brod simple&slim for various of users.
A producer process will not even try to keep messages in memory for retry in case of any exception when producing (e.g. socket error, error code received in produce response etc.)
It's up to the higher level caller how they want to handle the exceptions, e.g.
1. crash, restart later when partition leader switched over to another replica
2. try the next partition, like round-robin
3. persist on disk and retry later when the producer comes back

We will perhaps (this is still on top of my mind, have not yet communicated with the team) implement a higher level persistent producer on top of brod and put it here in github.
I'd be very interested to see how you would do it in case you get there first and opensource it.

**Comment by id** [comment]
Can we close this one now?

**Comment by Shnatsel** [comment]
> Can we close this one now?

Ah, I'd like to see the above points clarified in readme.md. I'll see if I can submit a pull request with fancy wording for this in a few days (rather busy schedule right now).

> We will perhaps implement a higher level persistent producer on top of brod

My thinking exactly, just push it into Mnesia ordered set and feed it to Brod from there.

**Comment by zmstone** [comment]
@Shnatsel I believe all your questions in the original post have been addressed in new README
I'm closing this issue now.
Feel free to reopen or create another one if there is anything unclear.
