### ISSUE TITLE
required_acks=0 only processes first message

### ISSUE THREAD

**Issue by byronpc** [kafka4beam/brod#65]
Hi,

I've just started exploring the driver. I notice that when required_acks = 0 (which if I'm not mistaken basically tells kafka to not send any acknowledgments), only the first message gets processed by the consumer. All succeeding messages are not consumed. 

Upon further investigation, it seems as if the driver is stuck on expecting a response or something? I'm not 100% sure as I have to delve into abit of code. But just incase you guys have any idea? 

I'm basically just calling

brod:produce(brod1, ?SESSION_TOPIC, ?RANDOM_PARTITION,  <<>>, J).

sync_produce will result in permanent waiting of response.

Please let me know.

Thanks!
Byron

**Comment by id** [comment]
Yes, looks like a bug in brod_producer_buffer. We'll have a look, thanks.

**Comment by byronpc** [comment]
You're welcome! Looking forward to a fix :)

**Comment by zmstone** [comment]
it's a fire-forget request, no need to call  sync_produce_request.
perhaps brod:produce should return ok instead of {ok, Ref} ?
