### ISSUE TITLE
snappy compression

### ISSUE THREAD

**Issue by zmstone** [kafka4beam/brod#68]

**Comment by vglukhovskiy** [comment]
Any idea when 2.2 would be available, please?

**Comment by zmstone** [comment]
Hi @vglukhovskiy we do not have a time plan.
Is snappy the specific feature you are looking for ?
(in case you didn't notice, we have gzip compression in place in 2.1.x release)
The snappy feature is pending on a work in progress Erlang snappy library.

**Comment by gg7** [comment]
> The snappy feature is pending on a work in progress Erlang snappy library.

What's wrong with [fdmanana/snappy-erlang-nif](https://github.com/fdmanana/snappy-erlang-nif)?

**Comment by zmstone** [comment]
@gg7 The major concern is: it's `nif`.
@id do you think we can go with nif, for now? since there is so far no ETA for the native snappy lib?

**Comment by id** [comment]
Yeah, let's go with nif for now.
