### ISSUE TITLE
lz4 compression

### ISSUE THREAD

**Issue by zmstone** [kafka4beam/brod#69]

**Comment by XOfSpades** [comment]
Is a support of lz4 planned in near future?

**Comment by zmstone** [comment]
@XOfSpades yes we have.
it's a work in progress.

**Comment by zmstone** [comment]
https://github.com/martinsumner/erlang-lz4
@qzhuyan ?

**Comment by qzhuyan** [comment]
Right I forget about my PR, will fix this week.

**Comment by zmstone** [comment]
it's to be added to kafka_protocol

**Comment by zmstone** [comment]
The latest `kafka_protocol` supports (a configurable callback) lz4 compression.
However it's not available to `brod` yet.
We will back port the feature to `kafka_protocol` 2.x
created this to follow up: https://github.com/kafka4beam/kafka_protocol/issues/88

Reopen this issue so we can follow up the changes in brod too

**Comment by tpitale** [comment]
Is there a reason `brod` hasn't updated to the latest `kafka_protocol` yet? Not sure if the changes are incompatible or something.

**Comment by zmstone** [comment]
> Is there a reason `brod` hasn't updated to the latest `kafka_protocol` yet? Not sure if the changes are incompatible or something.

hi. @tpitale, mostly because I have not managed to get the time for it.

The changes in kafka_protocol are incompatible. 
But hopefully we should be able to keep brod APIs compatible

**Comment by tpitale** [comment]
@zmstone I'm happy to take a run at the changes if you can point me in the general direction.

**Comment by zmstone** [comment]
@tpitale it's very nice of you to offer help.
let's move the discussion here: https://github.com/kafka4beam/brod/discussions/454
