### ISSUE TITLE
auto_start_producers doesn't seem to be working anymore

### ISSUE THREAD

**Issue by byronpc** [kafka4beam/brod#73]
have to explicitely call brod_client:start_producer before producer works otherwise it will return error producer_not_found

**Comment by byronpc** [comment]
i've investigated abit more...seems the location of auto_start_producers is different

Before 

`
{brod1, [
    {endpoints, [{"127.0.0.1", 9092}]},
    {config, [
        {reconnect_cool_down_seconds, 10},
        {auto_start_producers, true},
        {default_producer_config, [
            {required_acks, 0}
        ]}
    ]}
]}
`

After

`
{brod1, [
    {auto_start_producers, true},
    ....
]}
`

**Comment by zmstone** [comment]
yeah, right.
looks like it should've been a Major version bump.
we've tried to keep the APIs backward compatible to 2.0, but somehow missed this config change.
