### ISSUE TITLE
Metadata socket down

### ISSUE THREAD

**Issue by byronpc** [kafka4beam/brod#78]
Hi,

From what I understand, there is an occasional check for kafka metadata. However, I am getting these in the logs.

2016-05-30 08:33:49.887 [error] <0.282.0> CRASH REPORT Process <0.282.0> with 0 neighbours exited with reason: tcp_closed in brod_sock:handle_msg/3 line 214
2016-05-30 08:33:49.887 [error] <0.278.0> client brod1 metadata socket down 10.11.5.41:9092

If I'm not mistaken, tcp_closed is expected from the metadata socket after retrieval of inforight? Is this error expected as well? If this is expected, the only reason this error is appearing is because it's not properly handled?

Please enlighten me.

Thanks!

**Comment by zmstone** [comment]
Kafka shuts down from its end when the connection is idle for a while.
And brod will not try to re-connect immediately.
the re-connect is triggered by new metadata requests.

**Comment by id** [comment]
@zmstone we can probably change this https://github.com/klarna/brod/blob/master/src/brod_client.erl#L332 to error_logger:info_msg ?

**Comment by byronpc** [comment]
how about the crash report? It will still be a false alarm

**Comment by id** [comment]
That would be a bit more complicated. Normally we would like to see crash report from payload sockets and suppress those for metadata sockets.

I can think of a few possible options, will discuss with @zmstone .

**Comment by zmstone** [comment]
idle payload sockets also get closed by kafka.
we can perhaps suppress all remotely closed socket error logs.
