### ISSUE TITLE
Group subscriber supervision

### ISSUE THREAD

**Issue by Kwisatx** [kafka4beam/brod#97]
I implemented a pool of group subscribers as described in the Readme (and the demo module) to consume a topic in kafka. I didn't use the topic subscribers as we can have several agents running who share the load.

What I've been seeing however is that my group subscribers are crashing because of timeouts writing the offsets to kafka (not necessarily all at once). The subscribers are never restarted, meaning that after a few timeouts I don't have any subscribers left.

I've been working with brod 2.1.6, and I saw that in brod 2.1.9 subscribers should no longer crash if they can't write their offsets to kafka. However that doesn't solve the subscribers not being restarted if they crash some other way.

As such, how should I be supervising the group subscribers to ensure they don't die permanently?

**Comment by zmstone** [comment]
Hi @Kwisatx 
Brod takes care of connection restarts, as well as the restarts of direct partition workers (producer/consumer), but not for user spawned processes.
A group subscriber (same for a partition or topic subscriber) is to be managed by user application's supervisor for best flexibility.
We can perhaps introduce a supervisor in brod to manage all kinds of subscribers, but I would imagine the use cases are quite limited.

**Comment by Kwisatx** [comment]
Thanks for your answer, I was just a bit leery of starting the brod_group_subscriber processes directly from a supervisor instead of using the higher level api you provided (namely brod:start_link_group_subscriber), but since all it does is call brod_group_subscriber:start_link in the end... Working through a supervisor works nicely.
